### ISSUE TITLE
Can't delete the whole bookmark list at once. 

### ISSUE THREAD

**Issue by patrice-geo** [nextcloud/bookmarks#476] opened 2018-04-20 19:13 UTC
There is no way to delete ALL the bookmarks. We can delete bookmarks one by one, but there is no way to "clear" the whole bookmark list. 

I tried to disable the app, then remove it from the app list but everything is still there when re-enabling. 

Users and Admin are affected.

I doesn't make sense to delete 2000+ bookmarks one by one.

**Comment by marcelklehr** [comment] 2018-04-20 19:36
Duplicate of #157 #396 and #464. Confirmed. Fixed. Unreleased -- stay tuned for the upcoming release ;) Thanks for taking the time to give feedback. :)

**Comment by patrice-geo** [comment] 2018-04-20 20:27
Awesome, thanks!

**Comment by patrice-geo** [comment] 2018-07-09 11:44
I still can't find that feature in the latest version. Is it released yet? I don't want to put pressure ;)

**Comment by marcelklehr** [comment] 2018-07-09 17:22
It should be possible to select all visible bookmarks and then delete them all at once, so it's easier to delete them all, by displaying them all, selecting everything and then deleting them.

Still, you're right, there's no direct button to remove all bookmarks. In light of this, I'll reopen the issue.

**Comment by patrice-geo** [comment] 2018-07-16 11:21
But still, I can't seem to find the option to select all bookmarks so I could delete them all at once when they are selected. Is this feature available in the current stable version of Bookmarks?

**Comment by marcelklehr** [comment] 2018-07-16 18:46
Oh, now I understand. The feature is in the release candidate available on the app store (you'll have to install that one manually, for now).

**Comment by marcelklehr** [comment] 2018-07-17 21:55
(And while you try it, could you give feedback over at #522 ? Thanks :) )

**Comment by seth100** [comment] 2018-07-27 06:56
+1

**Closed as completed** 2018-07-28 13:57 UTC
Labels: enhancement

**Comment by marcelklehr** [comment] 2018-08-04 16:11
In RC5 there is now a button in the settings to clear all data from the current account. Happy testing :)
