### ISSUE TITLE
Bookmarklet doesn't add tags

### ISSUE THREAD

**Issue by blacs30** [nextcloud/bookmarks#539] opened 2018-07-29 15:18 UTC
### Steps to reproduce
1. Drag the bookmarklet into the bookmark bar in the browser
2. Open a page to add to bookmarks
3. click on the bookmarklet 
4. enter one or multiple tags
5. enter a description

### Expected behaviour
I expect that tags and description appear in bookmarks in nextcloud

### Actual behaviour
the bookmark is created but tags don't appear
_edit:_ the description is present

### Client Configuration
**Operating System:**
macOS 10.13.6

**Browser:**
Safari, Firefox, Chrome

### Server configuration
**Operating system**:
Debian 8.11

**Web server:**
nginx 1.12.2

**Database:**
mysql  Ver 14.14 Distrib 5.5.60

**PHP version:**
7.0.31

**Nextcloud version:** (see Nextcloud admin page)
13.5

**Bookmarks version:** (see Nextcloud apps page)
v0.12.0-rc4

**Comment by marcelklehr** [comment] 2018-07-29 19:02
Nice one! Thanks for testing

**Comment by marcelklehr** [comment] 2018-07-29 19:03
Actually I cannot reproduce the description failing to be added. Could you check that again?

**Comment by blacs30** [comment] 2018-07-29 20:32
I have updated the issue, sorry for my mistakes. The description appears fine, just the tags don't appear.
Added my client side specs in the original description.

**Comment by marcelklehr** [comment] 2018-07-30 00:02
Awesome, then your issue is fixed and the fix will be in the next release :) Thanks for reporting!

**Closed as completed by marcelklehr** 2018-07-30 00:02 UTC

**Comment by blacs30** [comment] 2018-08-05 10:17
Just tested it. Works like a charm. Thanks a lot!
