### ISSUE TITLE
Tags Menu is Covered in a Bookmark Details

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1554] opened 2021-05-17 17:38 UTC
**Describe the bug**
Tags menu is covered and there is no way to click and add some tags to a bookmark. The screenshot will explain the rest.

**To Reproduce**
1. Click a bookmark menu.
2. Check for details.
3. Click the tags menu.
4. Scroll up to find the tags.

**Expected behavior**
The tags menu is not covered so a user can add tags.

**Screenshots**
![1](https://user-images.githubusercontent.com/75371007/118531872-e91ecb00-b778-11eb-8e83-17a71cbac734.png)

**Desktop (please complete the following information):**
 - OS: openSUSE 15.2
 - Browser: Firefox
 - Version: 78.10.0esr

**Server (please complete the following information):**
 - OS: Alpine 3.13
 - HTTP server: nginx/1.18.0 
 - Database: mariadb  Ver 15.1 Distrib 10.5.9-MariaDB, for Linux (armv8l) using readline 5.1
 - PHP version: 7.4.19
 - Nextcloud version: 21.0.1
 - Bookmarks app version: 4.2.1
 - Activated Nextcloud Apps:
```
Enabled:
  - accessibility: 1.7.0
  - announcementcenter: 5.0.0
  - audioplayer: 3.1.0
  - bookmarks: 4.2.1
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - news: 15.4.3
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - passman: 2.3.8
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - federation
  - files_trashbin
  - issuetemplate
  - passwords
  - sharebymail
  - user_ldap
```
 - Nextcloud configuration:
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_language": "ja_JP",
        "default_locale": "ja_JP",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
``` 
 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
(Not an error.)
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
(Not an error.)
```

**Browser log**
```
(Not an error.)
```

**Comment by marcelklehr** [comment] 2021-05-17 18:20
Mh, I've seen this recently in another app, but was able to fix it by reloading the page.

**Comment by marcelklehr** [comment] 2021-06-09 16:37
I can't reproduce this with firefox 75 nor with latest chromium. Arguably that's not the latest firefox, so I'll hold off on closing this.

**Comment by HouraisanNEET** [comment] 2021-06-09 17:37
Also happens on a new instance.

**Screenshots**
![freebsd](https://user-images.githubusercontent.com/75371007/121401695-9c02d300-c98b-11eb-9930-e6a20223a725.png)

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.0
 - Browser: Firefox / Chromium
 - Version: 78.11.0esr / 90.0.4430.212

**Server (please complete the following information):**
 - OS: FreeBSD 13.0
 - HTTP server: nginx/1.18.0 
 - Database: SQLite
 - PHP version: 7.4.20
 - Nextcloud version: 21.0.2
 - Bookmarks app version: 4.2.1
 - Activated Nextcloud Apps:
```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bookmarks: 4.2.1
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - audioplayer
  - calendar
  - checksum
  - encryption
  - files_external
  - issuetemplate
  - news
  - notes
  - passwords
  - tasks
  - user_ldap
```

**Comment by eugulixes** [comment] 2021-06-24 17:47
I confirm the behaviour described by @HouraisanNEET.

![image](https://user-images.githubusercontent.com/5358223/123308685-a2b54c80-d52c-11eb-969c-9d9853315021.png)

The 3rd tag is missing.

Desktop:
* OS: Ubuntu 18.04
* Browser: Chrome
* Version:  91.0.4472.77 (Official Build) (64-bit)

Server:
* OS: Alpine 3.13
* HTTP server: Nginx 1.18.0
* Database: MariaDB 10.5.9
* PHP version: 7.4.19
* Nextcloud version: 21.0.2
* Bookmarks app version: 4.2.1

**Comment by marcelklehr** [comment] 2021-06-24 17:54
Ah, the problem appears when I reduce the browser window height.
Mmmh. @skjnldsv Any idea how to fix this? The multiselect [lives here](https://github.com/nextcloud/bookmarks/blob/master/src/components/SidebarBookmark.vue#L52) [nextcloud/vue is 3.7.2](https://github.com/nextcloud/bookmarks/blob/master/package.json#L29) -- would updating help?

**Comment by raimund-schluessler** [comment] 2021-06-25 07:15
I also noticed this for the Tasks app. I think the basic problem is the z-index of the header (don't remember for sure). I circumvented it by always opening Multiselects in the Sidebar towards the bottom by adding `open-direction="below`, see https://github.com/nextcloud/tasks/blob/master/src/components/AppSidebar/MultiselectItem.vue#L37 Not the ideal solution, but works for Tasks.

**Closed as completed** 2021-07-18 09:37 UTC
Labels: bug
