### ISSUE TITLE
Enable sharing of bookmarks to other users

### ISSUE THREAD

**Issue by LiamHD** [nextcloud/bookmarks#306] opened 2016-11-23 15:23 UTC
I would like to share some of my bookmarks to other NextCloud users similar to files.
Is this on your list?

**Comment by TheCelavi** [comment] 2016-12-21 08:32
We use owncloud in our small organization, bookmarks are used for referencing some interesting websites -> sharing of bookmarks would be AWESOME!!! Really useful!

**Comment by Tech-Port** [comment] 2016-12-21 08:57
That's exactly what we need!

**Comment by tflidd** [comment] 2017-01-04 10:32
duplicate of https://github.com/nextcloud/bookmarks/issues/5

**Closed by tflidd** 2017-01-04 10:32 UTC
Labels: duplicate
