### ISSUE TITLE
possibility of sharing

### ISSUE THREAD

**Issue by hercut** [nextcloud/bookmarks#453] opened 2018-03-15 08:43 UTC
It would be interesting to give the possibility to share folders with other nextcloud users.

This makes it possible to have favorites managed by several people of a team.

**Comment by marcelklehr** [comment] 2018-03-15 16:59
Hey @hercut :)
Thanks for taking the time to give feedback. We're thinking about how best to add sharing functionality to the app at the moment. See #5 for more information ;)

Closing this as a duplicate of #5 
Cheers!

**Closed as completed by marcelklehr** 2018-03-15 16:59 UTC
