### ISSUE TITLE
Dark Theme displays visual quirks

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#766] opened 2019-08-06 05:21 UTC
![tag-select](https://user-images.githubusercontent.com/1787238/62514178-3b287380-b7d3-11e9-924b-56a09b03a2f8.gif)

![dark-theme-bookmarks](https://user-images.githubusercontent.com/1787238/62512801-5775e180-b7ce-11e9-802e-b9fc74167549.png)

I find the grey on grey Bookmark visual styling confusing with the dark theme enabled in Accessibility.  Just noting it.  Thanks!

Selecting the description field is quirky as well. It would make sense to be white on a black background by default.
![description-dark-theme](https://user-images.githubusercontent.com/1787238/62513350-9ad14f80-b7d0-11e9-9445-4f2eef836773.gif)

The grey on white link displayed under Details is illegible in the web view.
![link](https://user-images.githubusercontent.com/1787238/62513392-cbb18480-b7d0-11e9-9a48-ba034d22cf48.png)
![tag](https://user-images.githubusercontent.com/1787238/62513481-13d0a700-b7d1-11e9-9b14-080fea6c0cac.png)

**Comment by marcelklehr** [comment] 2019-08-06 10:13
I think this is a duplicate of #596 
I'm working on a rewrite of the client-side code, which should resolve this among other issues.

**Closed as completed by marcelklehr** 2019-08-06 10:13 UTC
