### ISSUE TITLE
Implement installing as webAPK?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/bookmarks#1078] opened 2020-06-15 22:58 UTC
> With v3.2.0 released you can now install the nextcloud bookmarks web app as a progressive web app on your android or iOS phone.

Thank you very much for implementing this feature. It is working great! 

Would it be possible to feature the installment as "WebAPK"?
This would allow the PWA to become much more independent from the Browser and some other advantages.

Here are the docs:
https://developers.google.com/web/fundamentals/integration/webapks

> Being installed via an APK makes it possible for your app to show up in the app launcher, in Android's app settings and to register a set of intent filters.

_Originally posted by @szaimen in https://github.com/nextcloud/bookmarks/issues/1051#issuecomment-643833023_

**Comment by marcelklehr** [comment] 2020-06-16 09:16
Hello @szaimen 

I didn't know about WebAPKs. According to the article you linked this should be done automatically when installing the PWA in chrome.

**Comment by szaimen** [comment] 2020-06-16 10:23
Hi @marcelklehr unfortunately installing as WebAPK currently doesn't work automatically.
I've inspected the bookmarks app with "Google Chrome Lighthouse" and found those issues. I think the one that prevents installing is  "Does not register a service worker that controls page and start_url"
Here is the corresponding "Learn more" link: https://web.dev/service-worker/?utm_source=lighthouse&utm_medium=devtools
![image](https://user-images.githubusercontent.com/42591237/84762905-b352ee80-afcb-11ea-9e60-e4ee2c6ddc77.png)

**Comment by szaimen** [comment] 2020-06-16 10:35
@marcelklehr I am not sure but it could be problematic that there isn't a scope attribute defined inside the manifest; maybe this is the problem here.
https://web.dev/add-manifest/#scope

**Comment by szaimen** [comment] 2020-06-16 10:43
Here are some additional docs for the start_url and scope attributes.
https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url
https://developer.mozilla.org/en-US/docs/Web/Manifest/scope

**Comment by szaimen** [comment] 2020-06-16 10:55
I am not sure but adding the following line:
'scope' => $this->urlGenerator->linkToRouteAbsolute('bookmarks.web_view.index'),
here:
https://github.com/nextcloud/bookmarks/blob/master/lib/Controller/WebViewController.php#L155
Could solve the problem.

**Comment by szaimen** [comment] 2020-06-18 09:30
BTW: I get those errors in the console:
![image](https://user-images.githubusercontent.com/42591237/85003769-f2fa1180-b156-11ea-8e17-934d4808d182.png)
and this message in the "installable" section:
![image](https://user-images.githubusercontent.com/42591237/85003851-11600d00-b157-11ea-85db-6f43a2839b00.png)
Maybe it is related?

**Comment by szaimen** [comment] 2020-07-07 00:46
> BTW: I get those errors in the console:
> ![image](https://user-images.githubusercontent.com/42591237/85003769-f2fa1180-b156-11ea-8e17-934d4808d182.png)
> and this message in the "installable" section:
> ![image](https://user-images.githubusercontent.com/42591237/85003851-11600d00-b157-11ea-85db-6f43a2839b00.png)
> Maybe it is related?

After testing a bit further, I think that this is the main reason why it doesnt show up as beeing installable.
@marcelklehr Do you have an idea why it fails to install the service worker?
Maybe it is because the script isn't actually existing?

**Comment by szaimen** [comment] 2020-07-12 21:57
@marcelklehr Does the service-worker work on your installation? 
(No issue while registering the serviceworker -> listed as installable on Google Chrome Lighthouse.)

Here, you can find a working service-worker:
https://github.com/lindnerju/ePaeko/blob/master/service-worker.js

with the following webmanifest:
https://github.com/lindnerju/ePaeko/blob/master/manifest.webmanifest

The service-worker is called by:
https://github.com/lindnerju/ePaeko/blob/master/index.html#L38-L42

It might help you fix the service-worker. 
I am unfortunately not able to fix it myself since I am not a developer and have no dev setup for Nextcloud. 
The changes that I made to the productive instance seem to make no difference.

**Comment by marcelklehr** [comment] 2020-07-19 15:38
Mmmh, installation works with firefox but not with Chromium :/

**Comment by szaimen** [comment] 2020-07-19 18:54
> Mmmh, installation works with firefox but not with Chromium :/

Do you have the same error message there? 
> TypeError: failed to register a service worker for scope ... with script ... A bad http response was received when fetching the script



> Update: But that's only with my self-signed dev cert. On my prod server it works even in chrome.

Are you using a lets encrypt certificate on your prod server? If not, maybe it is a problem with lets encrypt certificates (which I am using).

Could you please have a look if you are seeing any Errors in the browser console when navigating to the bookmarks app on your prod server? This could help to debug the issue.

**Comment by marcelklehr** [comment] 2020-07-20 08:39
> Do you have the same error message there?

Nope, on my dev setup i get two different errors. One is about the TLS cert and the other about a CSP rule that forbids loading of the script.


On my prod server I'm using let's encrypt yep. In the console I get `ServiceWorker registered` so things look good there.

I notice you're using mod_rewrite, though. Maybe there's something going wrong there, causing it to 404. On my server the URL is `index.php/apps/bookmarks/` while it looks for `/apps/bookmarks/` on your server.

**Comment by marcelklehr** [comment] 2021-01-07 19:38
I'm closing this for now, as I cannot replicate your issue so far and there haven't been any updates. Feel free to give me a shout if this is still an issue.

**Comment by szaimen** [comment] 2021-01-07 19:51
Yes, its unfortunately still an issue and it seems like I cannot provide any sensible information on this to make it reproducible for you.
The only thing I can mention is, that I am using the Nextcloud VM and activated TLS using the built-in script.

So it should be reproducible following:
1. install [VM-Player](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html) or [VM-Fusion](https://www.vmware.com/products/fusion/fusion-evaluation.html)
2. Download the image from [here](https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N?path=%2F20.0.4%20-%20HUB) and import it into the program
3. run the initial script and set up Lets encrypt by running the built-in Activate TLS script
4. install the bookmarks app
5. now open the bookmarks app and you should see in Chrome that it fails to load the service worker.

**Comment by marcelklehr** [comment] 2021-08-13 13:28
I can't reproduce this, sorry.

**Comment by szaimen** [comment] 2021-08-23 13:30
I still have this problem. Seems like because of some reasons `https://myncdomain.com/index.php/apps/bookmarks/service-worker.js` works fine but not `https://myncdomain.com/apps/bookmarks/service-worker.js`. (pretty urls are enabled on my instance so the second link should work nonetheless)
So maybe always return index.php for the service worker here?
https://github.com/nextcloud/bookmarks/blob/03c57b377e27cb3dfbab41f6736044d0d384bf89/src/main.js#L37

**Comment by marcelklehr** [comment] 2021-08-23 14:51
`generateUrl` already [infers](https://github.com/nextcloud/nextcloud-router/blob/master/lib/index.ts#L108-L112), whether it should use `index.php`. Can you post your htaccess/nginx config?

**Comment by szaimen** [comment] 2021-08-23 15:00
Ah okay... I don't use nginx but apache and the default nextcloud .htaccess config.
You find the apache config here:
https://github.com/nextcloud/vm/blob/219e21d3b303f27c3a08d48f605e391e5724b7e7/lets-encrypt/activate-tls.sh#L131-L206

**Comment by szaimen** [comment] 2021-08-23 15:02
Does it work on your production instance if you enable pretty urls?

**Comment by marcelklehr** [comment] 2021-08-23 15:25
> Does it work on your production instance if you enable pretty urls?

Yes.

**Comment by marcelklehr** [comment] 2021-08-23 15:25
Maybe it's a nextcloud version thing? I've been successfully using this with nc 20 and 21

**Comment by szaimen** [comment] 2021-08-23 15:47
not sure... but seems to be setup related

**Comment by szaimen** [comment] 2022-09-03 18:07
Okay, I think I may have understood the problem now. As far as I know are all js files never routed through the index.php when pretty urls are activated via .htaccess. So In order to make this work, you need to add index.php manually also for these instances. `generateUrl` doesn't work here because it modifies the url to https://domain.com/apps/bookmarks/service-worker.js. however the file is not lying in that generated but only generrated on the fly. So here is one place where adding index.php needs to be consistantly added even when pretty urls are activated... Not sure how to work around this though. Any idea @marcelklehr?

**Comment by szaimen** [comment] 2022-09-03 18:35
found a fix in #1889

**Closed as completed** 2022-09-26 14:22 UTC
Labels: bug, javascript
