### ISSUE TITLE
0.12 RC1 freezes browser 

### ISSUE THREAD

**Issue by blizzz** [nextcloud/bookmarks#500] opened 2018-05-31 21:10 UTC
… with the bookmarks from my instance. I anonymized tags, urls and titles and created a dump for testing: 
[bookmarks.sql.txt](https://github.com/nextcloud/bookmarks/files/2060085/bookmarks.sql.txt)

could not do further testing yet :(

@marcelklehr

**Comment by marcelklehr** [comment] 2018-06-01 15:00
I've just successfully migrated from a new install of v0.11 (with arguably fewer bookmarks than you have :D) to rc1 :/ Gonna try and feed your mysql dump into my sqlite db now.

**Comment by marcelklehr** [comment] 2018-06-01 15:02
Do you get anything in the nextcloud log?

**Comment by marcelklehr** [comment] 2018-06-01 18:03
Mh. Trying to make SQLite swallow that dump was a waste of time :D 

When I source your dump in the mysql client I get

```
ERROR 1071 (42000) at line 25 in file: 'Downloads/bookmarks.sql (1).txt': Specified key was too long; max key length is 767 bytes
```

**Comment by blizzz** [comment] 2018-06-01 18:34
My mysql/mariadb database are utf8mb enabled

**Comment by marcelklehr** [comment] 2018-06-01 19:32
So, apparently it just takes a while for the data to load, then the browser unfreezes and everything works smoothly for me. Still, it's weird for the initial load of the bookmarks to be this slow, especially as the browser network tab says it spends all of those 3 minutes *downloading* 9kb, while, once it's loaded, the same amount of bookmarks takes 80ms on scroll...

**Comment by blizzz** [comment] 2018-06-01 20:16
Well, it does not get smooth for me somehow. something seems to be stuck still. perhaps the requests cause some lock.

**Comment by marcelklehr** [comment] 2018-06-01 20:31
So, chrome perf monitor says it spends all of that time on redrawing the same view over and over again as items from the request are loaded into the collection.

**Comment by marcelklehr** [comment] 2018-06-01 20:34
Tazing. Here's the fix: https://github.com/nextcloud/bookmarks/pull/502

**Comment by TtuxX** [comment] 2018-07-19 22:11
Hi @marcelklehr ! :)

I imported @blizzz's full SQL dump (replacing 'master' with my user name) and loading works perfectly well on my side, both on latest Firefox (desktop & mobile), and Chromium (desktop & mobile).

The only visible "issue" I do easily see at the moment (on my own bookmarks), is the one of issue https://github.com/nextcloud/bookmarks/issues/501, regarding thumbnails/website previews. For some sites it works, for some other (the majority for me), it does not.

Thank you for your work and I remain at your disposal should you require any help for testing your latest release. :)

**Comment by marcelklehr** [comment] 2018-07-20 10:06
Thanks for testing! In light of this, I'm closing this issue, as I can't reproduce this anymore either.

Regarding the thumbnails: The algorithm is not perfect. It was not possible to do an actual screen shot so we have to rely on using images that are embedded in the websites themselves. This is not always possible as some are using CSS to embed them. :/

**Closed as completed by marcelklehr** 2018-07-20 10:06 UTC
Labels: bug

**Comment by TtuxX** [comment] 2018-07-20 13:31
@marcelklehr 

I know it might be a lot of work, but.... given that previews have quite an important role in your new bookmarks application layout, what about the idea of imitating/implementing code from Marius Wieschollek, the maintener of the nextcloud Passwords app ? :))  (https://github.com/marius-wieschollek/passwords)

His app uses websites such as as https://www.screenshotapi.io/ for screenshots, and is very reliable :)

_Screenshot of the Password app in Nextcloud settings page:_

![image](https://user-images.githubusercontent.com/6570830/43004643-b241bbae-8c30-11e8-9969-de142de25fb9.png)

**Comment by blizzz** [comment] 2018-07-31 09:59
> His app uses websites such as as https://www.screenshotapi.io/ for screenshots, and is very reliable :)

However this is a service outside of your control.

**Comment by marcelklehr** [comment] 2018-07-31 13:48
> @marcelklehr solved it by implementing the http://screeenly.com/ open-source service, that can be hosted on your servers :)

... and is optional ;)
