### ISSUE TITLE
app store points to 3.4.7, but can't be loaded

### ISSUE THREAD

**Issue by oelison** [nextcloud/bookmarks#1308] opened 2020-11-04 12:24 UTC
**Describe the bug**
app can't be loaded from nextcloud apps

**To Reproduce**
Just go to your nextcloud instance and try to install bookmarks, when it is not installed

**Expected behavior**
I think it should point to version 3.4.9, because 3.4.7 is broken.

**result**
Client error: `GET https://github.com/nextcloud/bookmarks/releases/download/v3.4.7/bookmarks-3.4.7.tar.gz` resulted in a `404 Not Found` response: Not Found 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: actual

**Comment by marcelklehr** [comment] 2020-11-04 12:32
Duplicate of #1306

**Closed as completed by marcelklehr** 2020-11-04 12:32 UTC
Labels: bug

**Comment by oelison** [comment] 2020-11-04 13:00
it is loadin 3.4.9 now and all is fine.
thank you
