### ISSUE TITLE
Unable to bookmark a URL (on Nextcloud)

### ISSUE THREAD

**Issue by mmichler** [nextcloud/bookmarks#295] opened 2016-10-12 11:31 UTC
## Steps to reproduce
1. Paste URL `http://www.nytimes.com/2016/10/06/t-magazine/design/brutalist-architecture-revival.html` into the address field in the bookmarks app
2. Click the plus-button
3. Receive error message: `Could not add bookmark`
## Expected behaviour

The page should be bookmarked
## Actual behaviour

The bookmarks app fails to add the page
## Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.8

**Nextcloud version:** 10.0.1

**Bookmarks version:** 0.9.0

**Updated from an older Nextcloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tarball from download page

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
- activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.3
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - rainloop: 4.26
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocm1h9z6kosq",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "app.mail.smtplog.enabled": true,
        "mail_smtpmode": "php"
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 45.3 / Chrome 53.0.2785.143

**Operating system:** Debian Jessie
### Logs

I did not find any php errors connected to the bookmarks app in the logs

**Comment by blizzz** [comment] 2016-10-13 22:45
Thanks for the report, I also came across… will fix as soon as i find a little bit of time

**Comment by blizzz** [comment] 2016-10-14 14:54
Hm, now I cannot reproduce. By chance, have you been logged out before?

**Comment by oddmean** [comment] 2016-10-16 07:44
I have the same issue. Neither 'bookmarklet' nor the app's page seem to add bookmarks. When do you plan to release #290 ? And no, I haven't been logged out.

**Comment by blizzz** [comment] 2016-10-16 12:38
@oddmean anything in the logs? Could you try whether #290 fixes it?

**Comment by mmichler** [comment] 2016-10-17 07:29
@blizzz No, I have not been logged out - other URLs were bookmarked in the same session without problem. Only the nytimes.com page gave me trouble. This could be related to #257

**Comment by nidusin** [comment] 2016-10-21 00:01
Seems to me to only affect non HTTPS URLs from testing on my own.

**Comment by oddmean** [comment] 2016-10-21 05:12
@blizzz nothing related to 'Bookmarks' was there in logs. I've tried #290 but nothing changed. I'm still unable to add any bookmark.

**Comment by blizzz** [comment] 2016-10-21 08:26
@oddmean thanks for testing. Can you verify @nidusin s observation ?

**Comment by yorikvanhavre** [comment] 2016-10-24 16:31
Same problem here, #290 fixes the problem for me, and indeed it's a non-https instance of owncloud.

**Comment by oddmean** [comment] 2016-11-14 14:31
@blizzz no neither https, nor http sites could be added.

**Comment by blizzz** [comment] 2016-12-04 18:06
I fixed one issue when curl received unexpected response from the web server https://github.com/nextcloud/bookmarks/pull/312

Could you try that? Otherwise, please name domains where you experience issues so I can debug those cases.

**Comment by marcelklehr** [comment] 2018-02-10 21:38
I cannot reproduce this with the current version. Closing this for now. Please drop a message here, if you still experience this.

**Closed by marcelklehr** 2018-02-10 21:38 UTC
Labels: awaiting confirmation, bug
