### ISSUE TITLE
Unable to add URL for Intranet (private network ) websites

### ISSUE THREAD

**Issue by mrclll** [nextcloud/bookmarks#298] opened 2016-10-26 08:30 UTC
I'm able to add www.google.com but I can't add a private network URL.

**Comment by canglong** [comment] 2017-02-14 12:04
+1

I have several URLs that will only resolve internally. Would like the option to add them manually to NC.

**Comment by blizzz** [comment] 2017-02-15 12:10
Which versions are you using? IIRC it should work with 0.9.1.

**Comment by canglong** [comment] 2017-02-19 06:38
Just tested again, and its not working with 0.9.1 on NC 11.0.1.

Was able to work around it by bookmarking the URLs in firefox, and then import them to NC from CSV.

**Comment by blizzz** [comment] 2017-02-19 14:02
Well, it should appear after adding, not after another reload. In that way it would still be a bug.

**Comment by marcelklehr** [comment] 2018-06-24 18:47
I'm unable to reproduce this. Closing for now.

**Closed by marcelklehr** 2018-06-24 18:47 UTC
Labels: awaiting confirmation, bug
