### ISSUE TITLE
Android apps sync not working

### ISSUE THREAD

**Issue by tiptruck** [nextcloud/bookmarks#1051] opened 2020-05-27 10:05 UTC
Both Nextcloud Bookmarks and NC Bookmarks unable to sync with Nextcloud. Invalid URL

**Comment by muppeth** [comment] 2020-05-30 01:10
I can confirm (wanted to update to latest before). Tested on two independent instances.

**Comment by dasbiswajit** [comment] 2020-05-30 07:49
@tiptruck can you please open the issue [here](https://gitlab.com/bisada/OCBookmarks/-/issues) for android nextcloud bookmark android app bug.

**Comment by tiptruck** [comment] 2020-05-31 05:13
I can open an issue there but I think it is very unlikely this is due to the Android app. The sync is not working with Nextcloud Bookmarks and NC Bookmark Viewer and neither has been updated since 2018.

**Comment by marcelklehr** [comment] 2020-05-31 07:52
The problem is that I can't deduce much from the error message of the Android app.

**Comment by 0x9060** [comment] 2020-05-31 23:43
Same issue here. Tried syncing 3 Android apps from F-Droid store to my personal Nextcloud server. All failed, apparently invalid URL?

Running NC18 in Docker. I've synced other apps, including DAVx5 by providing a redirect to my reverse proxy (Traefik) from `.well-known` to `(card|cal)dav`. Wonder if something similar might be needed here? What is the relevant API endpoint for the Bookmarks integration?

**Comment by norfolkuncertainty** [comment] 2020-06-01 09:17
It appears that if you delete all of your bookmarks, authentication is again possible. However as soon as you add a bookmark with the web UI a "Connection Failed" Message appears down the bottom of the app. 
Subsequently adding a bookmark results in "Could not add bookmark", however the bookmark is actually added as requested.

**Comment by ksapp-dell** [comment] 2020-06-07 12:04
Hi,

so you use the latest version from play store  ? I ask, because the version for  f-droid is not supported since some time and the error you described was fixed in the play store version.

Regards
Oliver

**Comment by 0x9060** [comment] 2020-06-09 03:40
I do not have Google Play Store. I'm only using F-droid for apps. I *could* download Play Store apps using Aurora, but would prefer not to. Does this app rely on Google Play Services?

**Comment by ksapp-dell** [comment] 2020-06-09 06:02
Hi, 
The point is, that the F-droid version of the Android bookmark app is just to old and can not work together with the latest version of the Nextcloud bookmarks. 
The F-droid version is not maintained any more. 
You can check the comments at the Android bookmarks app developer website about this.
Regards
Oliver

**Comment by tiptruck** [comment] 2020-06-09 06:40
So this is a problem where the interface to Nextcloud bookmarks has changed and the Android apps need to be updated to work with it?

@marcelklehr looks to have found a solution anyway even if it is "uglomatic"

**Comment by dasbiswajit** [comment] 2020-06-09 06:57
@tiptruck please contact me I will share the latest Apk where you can install latest version. F-droid version I can not claim back.

**Comment by marcelklehr** [comment] 2020-06-10 11:15
@tiptruck Yes, I've managed to implement an old idea of mine to provide an alternative to native apps by offering the normal Web UI as a progressive web app, offline-capable and with the look-and-feel of a native app.

**Comment by marcelklehr** [comment] 2020-06-14 18:48
With v3.2.0 released you can now install the nextcloud bookmarks web app as a progressive web app on your android or iOS phone.

The issue with the native android app is half-resolved and in any case belongs on its gitlab repo.

**Closed as completed by marcelklehr** 2020-06-14 18:48 UTC

**Comment by szaimen** [comment] 2020-06-14 22:52
> With v3.2.0 released you can now install the nextcloud bookmarks web app as a progressive web app on your android or iOS phone.

Thank you very much for implementing this feature. It is working great! 

Would it be possible to feature the installment as "WebAPK"?
This would allow the PWA to become much more independent from the Browser and some other advantages.

Here are the docs:
https://developers.google.com/web/fundamentals/integration/webapks

**Comment by dasbiswajit** [comment] 2020-06-22 23:40
> @tiptruck please contact me I will share the latest Apk where you can install latest version. F-droid version is something we need to fix.



> Same issue here. Tried syncing 3 Android apps from F-Droid store to my personal Nextcloud server. All failed, apparently invalid URL?
> 
> Running NC18 in Docker. I've synced other apps, including DAVx5 by providing a redirect to my reverse proxy (Traefik) from `.well-known` to `(card|cal)dav`. Wonder if something similar might be needed here? What is the relevant API endpoint for the Bookmarks integration?

@muppeth @norfolkuncertainty @szaimen [f-droid](https://f-droid.org/packages/org.schabi.nxbookmarks) is live now. Please visit project [page](https://gitlab.com/bisada/OCBookmarks) for details.
