### ISSUE TITLE
Could not extract app bookmarks

### ISSUE THREAD

**Issue by brylie** [nextcloud/bookmarks#1269] opened 2020-10-21 08:46 UTC
**Describe the bug**
Cannot install bookmarks app on Nextcloud Hub 20.x

**To Reproduce**
1. Install Nextcloud Hub 20.x
2. Go to Applications screen
3. Click "Download and install"

**Expected behavior**
The plugin would install as normal.

**Screenshots**

![image](https://user-images.githubusercontent.com/17307/96695224-15649b80-1392-11eb-9ffa-055b8ae9eb8d.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Browser: Firefox 
 - Version: 81.0.2

**Server (please complete the following information):**
 - OS: Linux 5.4.65-1-pve x86_64
 - Database: MySQL 5.5.65
 - PHP version: 7.3.23
 - Nextcloud version:20.0
 - Bookmarks app version: 3.4.4

**Additional context**

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Exception: Could not extract app bookmarks

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:

    OC\Installer->downloadApp("bookmarks")

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Settings\Controller\AppSettingsController->enableApps([ "bookmarks"], [])

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/lib/base.php - line 1009:

    OC\Route\Router->match("/settings/apps/enable")

    /var/www/vhosts/sustainableurbandesign.space/httpdocs/nextcloud/index.php - line 37:

    OC::handleRequest()
```

**Comment by marcelklehr** [comment] 2020-10-21 10:35
this is a duplicate of #1256

**Closed as completed by marcelklehr** 2020-10-21 10:35 UTC
Labels: bug
