### ISSUE TITLE
Add Sharing / Use share api [$145]

### ISSUE THREAD

**Issue by eMerzh** [nextcloud/bookmarks#5] opened 2013-04-10 20:29 UTC
The Current version of bookmark does not allow to share bookmark using the sharing api.

Let the user share a tag with users and using a "private link".

Export a simple page with the bookmarks and an feed (atom, rss, ..) .

**Comment by pixi** [comment] 2015-02-24 08:45
Any news on the sharing?

**Comment by markus61** [comment] 2015-03-20 13:17
+1

**Comment by shaneonabike** [comment] 2015-04-11 18:03
I definitely think this would be really useful and practical to have the ability to share all your bookmarks or a few with other users like calendars

**Comment by BugHunter2k** [comment] 2015-08-09 11:18
Any News? I'd like to see this too.

**Comment by ronnystandtke** [comment] 2015-08-13 07:25
Another +1. We would like to share a collection of bookmarks for a project with external people (they have no user account on our ownCloud instance). We already share some files with these external people via a public link. It would be cool if we could just integrate our bookmarks into this shared file folder as clickable links (maybe even visually separated from the ordinary shared files and folders). This way we only have to share one link and everything that is needed for our project is easily accessible for our external people.

**Comment by brozkeff** [comment] 2015-08-17 11:33
+1
Our company is looking exactly for this functionality, lack of sharing in current bookmarks implementation means it is useless for us at this moment.

**Comment by pascaldaniela** [comment] 2015-09-08 13:44
+1
exactly what we're looking for to avoid having yet another service to add in our organization. Could we have any feedback from an owncloud developer?
thanks!

**Comment by xila76** [comment] 2015-11-26 10:10
:+1:

**Comment by ChrisEastGaming** [comment] 2016-06-20 11:52
Hey! You can get free, steam games. If you can get please click the link. It's very important for me. No virus! 100% work! Just one click. Please.
 https://steamgifts.co/go/?id=RvqdcyTKd

**Comment by TheNomad11** [comment] 2016-10-24 11:08
Yes, please, I actually expected this feature when I installed it :)

**Comment by marcelklehr** [comment] 2016-11-14 19:57
:+1: :)

**Comment by Endogen** [comment] 2017-05-07 18:30
Any news on this? I would really love to have this feature

**Comment by marcelklehr** [comment] 2017-05-07 20:36
This is the status quo on this feature:
Currently, there is a database field for each bookmark reserved to hold information whether it is public or private. The API can handle the field and even querying it is supported, so you can for example retrieve the public bookmarks of a specific user.

So going forward, we'd have to discuss the exact concept for sharing, specifically whether a private/public mode is sufficient (I've never used the sharing API myself, so I'd have to do some reading on it). Also, some concept would need to be developed for how sharing should work in the ui.

I'm open to implementing this, but the ETA is unknown as of yet.

**Comment by ccoenen** [comment] 2017-05-07 21:03
My personal use case is "_hey, everybody! This is stuff worth reading!_" - which is a subset of my bookmarks. Having only public and private would be totally fine for me.

**Comment by oparoz** [comment] 2017-05-15 11:02
Ultimately, I'd like to see the full sidebar implemented, but that requires changes in the server part.

In the meantime, something like the Gallery or Deck sharing dialogue could be implemented, making it easy to share bookmarks with other users or even publicly via a link.

**Comment by blizzz** [comment] 2017-05-15 12:07
The sidebar  crossed my mind recently as well. The UI could use some love anyhow.

**Comment by marcelklehr** [comment] 2017-05-15 18:47
Sharing would also be nice for tags, so you don't need to manually share every new bookmark you add to a tag.

**Comment by 9662** [comment] 2017-05-20 08:28
> My personal use case is "hey, everybody! This is stuff worth reading!" 

And FWIW, in addition to the above mine would be to share bookmarks within an organisation, so e.g., sharing with a specific group or user.

I guess in the long term a common sharing philosophy for all Nextcloud apps would be desirable, though this is way out of the scope of this issue.

**Comment by Laykou** [comment] 2017-08-16 08:24
👍

**Comment by ventolinmono** [comment] 2017-10-22 20:26
+1

**Comment by joe-speedboat** [comment] 2017-11-14 09:54
+1

**Comment by loranger** [comment] 2017-11-30 11:44
+1

**Comment by blizzz** [comment] 2017-12-03 21:42
Thanks for the feedback. However, more +1 won't make this happen. Code will make this happen :)

**Comment by marcelklehr** [comment] 2018-02-12 23:16
Alrighty, so let me propose the following:

### Features
Ideally we would want the following features

1. sharing single bookmarks via 3-dot-menu in bookmark tile
2. sharing a tag via tag list on the left (via 3-dot-menu of the tag)
3. both cases should open a sidebar on the right with all options, which are
   a. like in Files: other nc users, federated sharing, public links (sharing a single bookmark via a public link is kinda pointless, though, no?)

### Implementation
How do we implement this?

1. sharing bookmarks within the realms of one instance would theoretically be possible by sharing the ids directly. But this would also share added tags. This might be useful, but it could also be messing up people's personal organization, since everybody probably has their own system of tagging bookmarks.
2. similarly sharing a tag within the realms of one instance would be possible by having a separate table that stores which tags are shared among which users. In this case if user A already has a tag named foo, and B shares their foo tag with A, user A's bookmarks in foo would be merged with user B's bookmarks in foo, which is not a good solution IMO

To avoid # 1 we could "copy" the shared bookmark and keep a reference to the original in the table entry. This would also allow federated sharing by referencing user, nc url and id of the original bookmark. The original bookmark would have to be updated whenever the copied one is being updated and vice versa (probably requiring polling, in the case of federated sharing -- I'm not sure how this is usually handled in Nextcloud; The question then would be whether edits to the "copied" bookmark should be possible in case the remote end is unavailable / doesn't allow edits, as this would probably create a conflict that is not easy to reconcile).

To avoid # 2 we could introduce a different kind of tag which is a shared-with-you tag that cannot be removed nor added manually. This tag entry in the DB would reference user, nc url and tag name of the original tag. It would still be necessary to "copy" the tagged bookmarks as suggested above, since we don't want to ~~overtag~~ overtake all tags of the sharer.

There would also need to be tables for holding sharee permissions and public links.
### Drawbacks / Limitations

1. It's not possible to share combinations of tags (which kind of resemble folder paths)

---
cc @nextcloud/sharing @MorrisJobke @juliushaertl @jancborchardt

**Comment by 9662** [comment] 2018-02-19 00:45
@marcelklehr 

### Point 1
> it could also be messing up people's personal organization, since everybody probably has their own system of tagging bookmarks.

In which cases would people be sharing within an instance? My guess is that this is most likely to be an organisation where people are working together and communicate via channels other than sending each other bookmarks, so there is a good chance that there will be some sort of tagging convention, or one will emerge as they start sharing.

I don't think this will be a problem. If it is, it can always be fixed latter. ☺

### Point 2
> if user A already has a tag named foo, and B shares their foo tag with A, user A's bookmarks in foo would be merged with user B's bookmarks in foo, which is not a good solution IMO

Do you mean visually merged, or merged in the database? The former is clearly a feature, not a problem. That is what people do all the time with “hashtags”, don't they? The latter is more of a problem than a feature, I agree.

---

I am not sure if a little user story would help, but in my organisation we would love to be able to share tags with each other. For example:

I, 9662, have these bookmarks:

Bookmark | Tags
--------------|----------
Frobnicator | `project-a`, `materials`
Joe Blogs Consulting | `project-a`, `people`
Divide and Conquer Accountants | `project-a`, `people`

And my colleague 9663 has these:

Bookmark | Tags
--------------|-------
Whachamacallit Mk 2 | `project-b` `materials`
Jeanne Blarg | `project-b`, `people`
Sharks 'r Us Lending Co. | `project-b`, `finance`
Divide and Conquer Accountants | `project-b`, `people`

Now I share `project-a` with 9663 and he kindly shares `project-b` with me. Each of us will see this:

Bookmark | Tags
--------------|------
Frobnicator | `project-a`, `materials`
Whachamacallit Mk 2 | `project-b` `materials`
Joe Blogs Consulting | `project-a`, `people`
Jeanne Blarg | `project-b`, `people`
Sharks 'r Us Lending Co. | `project-b`, `finance`
Divide and Conquer Accountants | `project-a`, `project-b`, `people`

Note how the other tags are carried over, even though we only shared `project-a` and `project-b`, and how they are merged with the sharee's content. There would also be loss of information if the other tags were not implicitly shared, although this behaviour may not always be desirable and could be simulated by sharing all relevant tags.

---

Of course, this would probably be much easier if we had the ability to create multiple bookmark collections, in which case you would just share the whole collection with other users, much in the same way as https://github.com/nextcloud/deck does it.

**Comment by marcelklehr** [comment] 2018-02-23 21:39
@9662 Thanks for the input! I guess it can make sense to have the sharing system more transparent to allow sharing of attributed tags along with the shared bookmarks. We could of course make this optional (to add some more complexity :D), but I'd rather settle for one of the two approaches. (@jancborchardt  any advice appreaciated :) )

btw, for reference https://github.com/nextcloud/bookmarks/issues/405 (the issue re: collections)

**Comment by jancborchardt** [comment] 2018-02-26 10:29
Are "collections" the same as tags? Cause we should only have one system of organization/categorization.

And then it's simple:
- Allow sharing of single bookmarks
- Allow sharing of a "category" (in Bookmarks that would be a Tag, right?)

**Comment by rullzer** [comment] 2018-02-26 20:43
Just a quick FYI. The current sharing in the server is for files. So if you want to do sharing just create a 'bookmarks_share' table or whatever and put the info you need in there.

**Comment by marcelklehr** [comment] 2018-02-26 22:39
@rullzer Ah, thanks :) I had realized this some time ago :D 
Do you cache anything that is shared from a different server, btw?

**Comment by marcelklehr** [comment] 2018-02-26 22:42
@jancborchardt The question for me in the above post was whether shared bookmarks should retain the tags they were assigned by the sharer, or if the sharee shouldn't be able to see those / shouldn't have their tagging system interfered with, since people have different tagging systems. I'm coming from the idea that tags replace a folder hiearchy, but e.g. in the files app you don't share the whole path to the file but only the file itself, leaving the sharee free to put it where they want to have it.

**Comment by rullzer** [comment] 2018-02-27 10:10
@marcelklehr we do not with sharing files. Because then you get in weird situation where there are multiple versions of a file ;)

**Comment by tuxedoherbert** [comment] 2018-11-12 23:45
Hi at all,

I just want to bring this topic up again. Does anybody want to spent any time into this?

thanks a lot!

**Comment by jancborchardt** [comment] 2018-12-04 14:54
@tuxedoherbert there is a bounty on this issue you can donate to: https://www.bountysource.com/issues/1692470-add-sharing-use-share-api – this will help support any volunteer who wants to work on this issue.

Same for everyone else who commented and is interested in this issue:
**[💸 If you can, please donate to the bounty on this issue](https://www.bountysource.com/issues/1692470-add-sharing-use-share-api)** (it’s currently at only $15.

**Comment by small1** [comment] 2019-02-27 19:52
I have had requests for this and added 100 usd on the bounty.

**Comment by jothoma1** [comment] 2019-04-25 08:14
Interested in this too :) lots of use case for public schools, share bookmarks with group of students or teachers

**Comment by JesseSteele** [comment] 2019-06-23 04:11
Dear all, I've thought about contributing code to this. BUT, Nextcloud devs like to keep their code neatly knit together. Sharing bookmarks would be a deep project and, guessing how they work from what I see, their team is probably already solving this "issue" at a much deeper level in their code. It takes time, but it is what makes Nextcloud stable. And so, we may have to wait a little while, but not forever. Stay patient — IMHO

**Comment by ccoenen** [comment] 2019-06-23 09:38
Perhaps someone from the nextcloud team could verify or debunk this? Having this comment here based on a bunch of assumptions and beliefs might deter someone from _actually_ contributing code?

**Comment by marcelklehr** [comment] 2019-06-23 11:23
Yes, I can assure you that this is on my agenda :)

**Comment by mmeinesz** [comment] 2019-11-13 06:10
+1 for bookmark sharing

**Comment by marcelklehr** [comment] 2019-11-29 00:04
... while I have you folks here, what, if there is one, is the use case for sharing a single bookmark with another user? Sharing folders makes sense, sharing a single *file* makes sense, too, but sharing a single bookmark?

**Comment by ccoenen** [comment] 2019-11-29 17:50
Personally, I can't imagine the case for "single" link share. Perhaps other than link-shortener and tracking stuff, both of which I would actively like to avoid. It's a web-breaking practice mostly used to spy on people. In my opinion, share a bundle/folder/collection/whatever of links.

If you need to share "just one", put it in a collection or pass on the link directly.

**Comment by sunjam** [comment] 2019-12-11 15:10
The main strength of individual link sharing I can think of is to send a link to Wallabag, as intended in issue #524, otherwise I'll stick to sharing by group or tag

**Comment by ccoenen** [comment] 2019-12-11 18:11
I think the word "share" is used for very different things in these two cases. In this case here, it's about "I want to give this list of links to people with (or without) accounts", in that other one, it's more like "automatically integrate wallabag and bookmarks", I think we should keep these two cases seperate.

**Comment by 12nick12** [comment] 2020-01-30 02:13
Just to add a comment. I'd like to be able to share bookmarks like a folder. So I could make a shopping list and share it with people who and don't have accounts. Just like file folders.

**Comment by alexanderdd** [comment] 2020-03-22 22:14
@marcelklehr do I understand correctly that the UI is the only thing missing? See checklist here https://github.com/nextcloud/bookmarks/pull/870
Would it be helpful if we provide some mockups?

**Comment by marcelklehr** [comment] 2020-03-22 22:33
I'm sorry for the wait. I got sidetracked because I decided to refactor the db schema again. (And because floccus needed a lot of bugfixes.) I have some idea of how the UI might look like, especially, since there are quite a few reusable nextcloud components now. I have the server-side tests passing again, now, and will be able to focus on the UI next week, thanks to the corona shut down. :)

**Comment by marcelklehr** [comment] 2020-03-30 15:24
If you are technically inclined you may want to give https://github.com/nextcloud/bookmarks/pull/952 a go -- preferably on a testing instance or after making a database backup. Instructions on how to install are [in the README](https://github.com/nextcloud/bookmarks#manual-install).

**Comment by marcelklehr** [comment] 2020-04-09 10:13
...and here's the first beta version: https://github.com/nextcloud/bookmarks/issues/965

**Comment by marcelklehr** [comment] 2020-04-30 05:15
:sparkles:

**Closed** 2020-04-30 05:35 UTC
Labels: bounty, enhancement
