### ISSUE TITLE
Bookmarks not showing anymore

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/bookmarks#1588] opened 2021-06-19 17:12 UTC
**Describe the bug**
Bookmarks are stored but suddenly I can't see them anymore. It looks like folder is empty even though it show in the counter that they are stored and if I export bookmarks I got them.

**To Reproduce**
1. Go to a folder
2. See it's empty 

**Expected behavior**
I should see bookmarks stored in the folder

**Desktop (please complete the following information):**
 - OS: Mac 10.4.6
 - Browser: Firefox 89. Tested also on Chromium.

**Server (please complete the following information):**
 - OS: Debian
 - Nextcloud version: 20.0.8
 - Bookmarks app version: 4.2.2

**Browser log**
```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 4
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Notifications permissions denied App.vue:302
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Search is deprecated. Please use the unified search API instead search.js:31:10
oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20 globals.js:60:15
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Impossible d’inscrire/mettre à jour un service worker pour la portée « https://xxxx.io/nimbus/apps/bookmarks/ » : l’accès au stockage est limité dans ce contexte en raison des paramètres de l’utilisateur ou du mode de navigation privée. bookmarks-main.js:1853:128971
DOMException: The operation is insecure. bookmarks-main.js:1853:129111
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 10
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 120 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:18
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
XHRGEThttps://xxxx.io/nimbus/apps/bookmarks/bookmark?limit=42&page=0&sortby=lastmodified&folder=-1
[HTTP/2 500 Internal Server Error 289ms]

Error: Request failed with status code 500
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1144
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1839
    onreadystatechange https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1144
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1144
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1144
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1839
    promise callback*c.prototype.request https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1839
    e https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1839
    exports https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1144
    FETCH_PAGE https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    FILTER_BY_FOLDER https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    onRoute https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    created https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    Ge https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    qt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    i https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    componentInstance https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    En https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
bookmarks-main.js:1:20980
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
TypeError: this.$refs.input is undefined
    mounted https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    Ge https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    qt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    insert https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    x https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    run https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    An https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    tt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    Je https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    promise callback*$e https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    tt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    notify https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    set https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    Te https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    FETCH_END https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    commit https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    commit https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    _withCommit https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    commit https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    commit https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    promise callback*FETCH_PAGE https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    FILTER_BY_FOLDER https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    onRoute https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    created https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    Ge https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    qt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    i https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    componentInstance https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    En https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
bookmarks-main.js:7:11622
Uncaught (in promise) TypeError: m.a.t is not a function
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    promise callback*FETCH_PAGE https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    FILTER_BY_FOLDER https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    f https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:637
    dispatch https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:631
    onRoute https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    created https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1112
    Ge https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    qt https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    i https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    componentInstance https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    m https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    co https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _update https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    s https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    get https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    un https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    $mount https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    _init https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    En https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:7
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1853
    n https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
    <anonymous> https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0:1
bookmarks-main.js:1:21034
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 2
Erreur dans les liens source : Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL de la ressource : https://xxxx.io/nimbus/apps/bookmarks/js/bookmarks-main.js?v=1618dda0-0
URL du lien source : bookmarks-main.js.map?v=43ec481df40dc3d171a5

Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: Ce site (https://xxxx.io) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 2
XHRGEThttps://xxxx.io/nimbus/apps/bookmarks/folder/2/publictoken
[HTTP/2 404 Not Found 312ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 76 globals.js:60:15
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 8 util.js:130:10
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 8 util.js:130:10
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 8 util.js:130:10
```

Thanks for your help ! This app is very promising :)

**Comment by marcelklehr** [comment] 2021-06-19 17:26
Hi @ImaCrea, Sorry for your troubles, I'll try to help troubleshoot. 

> Error: Request failed with status code 500

Looks like this is an error on the server-side. An excerpt of the nextcloud log would be useful.

**Comment by ImaCrea** [comment] 2021-06-20 15:32
Sure, would be of great help if you could tell me how I can get them please :)

**Comment by marcelklehr** [comment] 2021-06-20 16:54
https://docs.nextcloud.com/server/19/admin_manual/issues/general_troubleshooting.html#logfiles

**Comment by ImaCrea** [comment] 2021-07-02 12:10
> See https://docs.nextcloud.com/server/19/admin_manual/issues/general_troubleshooting.html#logfiles

I'm having difficulties even with the guide :/ I'll try again when I have time.

**Comment by TiberiusRegenschein** [comment] 2021-07-04 13:57
I have the same issue and get the following log:

[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1728
    Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Doctrine\DBAL\Driver\PDO\Exception {}, Doctrine\DBAL\Query {})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1667
    Doctrine\DBAL\Connection->handleDriverException(Doctrine\DBAL\Driver\PDO\Exception {}, Doctrine\DBAL\Query {})
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1040
    Doctrine\DBAL\Connection->convertExceptionDuringQuery(Doctrine\DBAL\Driver\PDO\Exception {}, "SELECT `b`.`id` ... 2", ["bookmark","boo ... "], [2,2,2,2,2,"And  ... "])
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 226
    Doctrine\DBAL\Connection->executeQuery("SELECT `b`.`id` ... 2", ["bookmark","boo ... "], [2,2,2,2,2,"And  ... "], null)
 4. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 210
    OC\DB\Connection->executeQuery("SELECT `b`.`id` ... 2", ["bookmark","boo ... "], [2,2,2,2,2,"And  ... "])
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 287
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 323
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/nextcloud/apps/bookmarks/lib/Db/BookmarkMapper.php line 228
    OCP\AppFramework\Db\QBMapper->findEntities(OC\DB\QueryBuilder\QueryBuilder {})
 8. /var/www/nextcloud/apps/bookmarks/lib/Controller/BookmarkController.php line 363
    OCA\Bookmarks\Db\BookmarkMapper->findAll("thomas", OCA\Bookmarks\QueryParameters {})
 9. /var/www/nextcloud/apps/bookmarks/lib/Controller/InternalBookmarkController.php line 77
    OCA\Bookmarks\Controller\BookmarkController->getBookmarks(0, [], "or", "clickcount", [], 42, false, -1, null, null, null)
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 218
    OCA\Bookmarks\Controller\InternalBookmarkController->getBookmarks(0, [], "or", "clickcount", [], 42, false, "-1", null, null, null)
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 127
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmarks\Co ... {}, "getBookmarks")
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 157
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarks")
13. /var/www/nextcloud/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarks", OC\AppFramework\ ... {}, {_route: "bookma ... "})
14. /var/www/nextcloud/lib/base.php line 993
    OC\Route\Router->match("/apps/bookmarks/bookmark")
15. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /nextcloud/apps/bookmarks/bookmark?limit=42&page=0&sortby=clickcount&folder=-1
from 188.174.159.138 by thomas at 2021-07-04T13:53:23+00:00

**Comment by marcelklehr** [comment] 2021-07-14 19:02
Aha. Sorry for the delay. I can confirm this. The reason is a missing index for the clickcount column. Quick fix is to use a different sort order, long term fix will be in the next release.

**Closed as completed** 2021-07-18 09:56 UTC
Labels: bug
