### ISSUE TITLE
[Feature request] show bookmarks without tags

### ISSUE THREAD

**Issue by thinking-aloud** [nextcloud/bookmarks#172] opened 2015-07-12 15:53 UTC
I like to keep recent bookmarks without tags. Now, they are somewhere between the other bookmarks. 
It would be nice if it was possible to hide all bookmarks with tags or select "bookmarks without tags".

Implementing the sort feature would be an alternative. https://github.com/owncloud/bookmarks/issues/3

**Comment by blizzz** [comment] 2015-07-14 10:31
Good point. I thought i saw it mentioned in another issue but cannot find it right now or i mixed something up.

**Comment by jforce** [comment] 2015-07-14 14:59
thinking-aloud that is a good feature in my opinion

**Comment by marcelklehr** [comment] 2017-08-13 13:07
closing as a duplicate of #12

**Closed by marcelklehr** 2017-08-13 13:07 UTC
Labels: enhancement
