### ISSUE TITLE
Main URL (#all) won't load

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/bookmarks#650] opened 2019-01-26 19:31 UTC
Just migrated an older NC stable 12 to 13 and then to stable14, and bookmarks main page won't load.
In the Chrome console i get see the following errors:

main.bundle.js?v=aa76d404-15:21194 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at child.getColor (main.bundle.js?v=aa76d404-15:21194)
    at child.onRender (main.bundle.js?v=aa76d404-15:34399)
    at child.triggerMethod (main.bundle.js?v=aa76d404-15:21526)
    at child.triggerMethod$$1 [as triggerMethod] (main.bundle.js?v=aa76d404-15:22730)
    at child.render (main.bundle.js?v=aa76d404-15:23571)
    at renderView (main.bundle.js?v=aa76d404-15:22788)
    at child.addChildView (main.bundle.js?v=aa76d404-15:24379)
    at child._addChild (main.bundle.js?v=aa76d404-15:24349)
    at Function._.each._.forEach (main.bundle.js?v=aa76d404-15:2150)
    at child._showCollection (main.bundle.js?v=aa76d404-15:24197)

PHP 7.2, MariaDB 10.1.x, CentOS 7 and Bookmarks 0.16.0
Nextcloud stable14

**Comment by marcelklehr** [comment] 2019-01-26 20:14
Hey,
thank you for reporting this! It seems like this is a duplicate of #642 
I will publish a bugfix as soon as possible.

**Closed as completed by marcelklehr** 2019-01-26 20:14 UTC
