### ISSUE TITLE
I become an Error message when opening the Bookmarks tab

### ISSUE THREAD

**Issue by TonKkkkk** [nextcloud/bookmarks#1456] opened 2021-03-11 17:44 UTC
**Describe the bug**
After I installed the Bookmarks I once saw the correct screen.
After installing Firefox Floccus plugin and succesfully adding token autentication I was not able to sync via floccus or open the bookmark screen in Nextcloud

**To Reproduce**
Click on the Bookmarks Icon, as in the screenshot, error message as below in screenshot apears
![image](https://user-images.githubusercontent.com/48412952/110829147-19894b00-8298-11eb-9962-971b995a0e02.png)

**Expected behavior**
I get the Bookmarks screen, as I saw after installing

**Screenshots**
![image](https://user-images.githubusercontent.com/48412952/110828768-ac75b580-8297-11eb-9102-364b7c445332.png)

**Desktop (please complete the following information):**
 - OS: Mint Linux 20
 - Browser: Firefox
 - Version: 86

**Server (please complete the following information):**
 - OS: Ubuntu 18
 - HTTP server: from nextcloud docker image
 - Database: MariaDB 10.5]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: 21
 - Bookmarks app version: 4.1.0
 - Activated Nextcloud Apps: 
 - Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bookmarks: 4.1.0
  - calendar: 2.1.3
  - checksum: 1.1.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - apporder
  - encryption
  - files_external
  - mail
  - maps
  - socialsharing_email
  - unsplash
  - user_ldap

 - Nextcloud configuration:
 - {
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx",
            "192.168.xx.xx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.0.18",
        "overwrite.cli.url": "http:\/\/server",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}
 - Nextcloud external user backend: none

**Additional context**
Occurred after sync with floccus Firefox browser plugin sync ( probabely )

**Nextcloud error log**
{"reqId":"g6S1oiE10m075gijFkId","level":3,"time":"2021-03-11T17:22:40+00:00","remoteAddr":"192.168.xx.xx","user":"xxx","app":"index","method":"GET","url":"/apps/bookmarks/","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Bookmarks\\Db\\TreeMapper::getSubFolders() must be of the type int, null given, called in /var/www/html/custom_apps/bookmarks/lib/Controller/FoldersController.php on line 466","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\WebViewController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\WebViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.web_view.index"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Bookmarks\\Db\\TreeMapper::getSubFolders() must be of the type int, null given, called in /var/www/html/custom_apps/bookmarks/lib/Controller/FoldersController.php on line 466","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/bookmarks/lib/Controller/FoldersController.php","line":466,"function":"getSubFolders","class":"OCA\\Bookmarks\\Db\\TreeMapper","type":"->","args":[null,-1]},{"file":"/var/www/html/custom_apps/bookmarks/lib/Controller/WebViewController.php","line":109,"function":"getFolders","class":"OCA\\Bookmarks\\Controller\\FoldersController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\Bookmarks\\Controller\\WebViewController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\WebViewController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\WebViewController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\WebViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.web_view.index"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/bookmarks/lib/Db/TreeMapper.php","Line":708},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18"}

**Comment by Pinaute** [comment] 2021-03-13 16:16
Hi,
I looked at the logs, I have the same error, but for all I know only one user is affected by the bug and not using floccus.
I installed the plugin a day ago.

**Comment by marcelklehr** [comment] 2021-03-13 18:49
Thanks for reporting! I will look into this soon :)

**Comment by marcelklehr** [comment] 2021-03-22 20:20
This looks like the following issue https://github.com/nextcloud/bookmarks/issues/1467

Can you verify this?

**Comment by TonKkkkk** [comment] 2021-03-23 16:35
Thanks for the hint, had a look in the referenced issue and used the described database commando's.
**It looks for me that i do not have the "oc_bookmarks_root_folders" or the "oc_bookmarks_tree" in the database**, or I did something wrong in the database commands.
So in case the entries are not in the database it could be the same "output" as #1467 but from a different source.

The output of my commands is:

```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| nextcloud          |
| performance_schema |
+--------------------+

MariaDB [(none)]> use nextcloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

MariaDB [nextcloud]> SELECT * from oc_bookmarks_root_folders WHERE user_id = 'ton';
**ERROR 1146 (42S02): Table 'nextcloud.oc_bookmarks_root_folders' doesn't exist**

MariaDB [nextcloud]> SELECT * from oc_bookmarks_tree;
**ERROR 1146 (42S02): Table 'nextcloud.oc_bookmarks_tree' doesn't exist**
```

**Comment by marcelklehr** [comment] 2021-03-23 17:19
That's suspicious, though. Can you try `SHOW TABLES;` in the nextcloud database? If there are no bookmarks tables at all in there, then you'd have much more severe errors, I think.

**Comment by Pinaute** [comment] 2021-03-23 17:31
@TonKkkkk 
Perhaps try with `bookmarks_root_folders` instead of `oc_bookmarks_root_folders` ?

**Comment by Pinaute** [comment] 2021-03-23 17:39
With the user impacted by the error, I see two root folders. 
The other users have only one root folder.
```
psql (9.6.1)
Type "help" for help.

nextcloud=# SELECT * from bookmarks_root_folders WHERE user_id = 'eric';
 user_id | folder_id 
---------+-----------
 eric    |         5
 eric    |         6
(2 rows)
```

**Comment by marcelklehr** [comment] 2021-03-23 17:52
@Pinaute Then you can continue as outlined in https://github.com/nextcloud/bookmarks/issues/1467#issuecomment-803676461

I will probably create a repair step for this so, other people don't have to do this manually in the future.

**Comment by TonKkkkk** [comment] 2021-03-23 19:09
Yes it looks like the tables are named different, without oc_.
Is this OK, where does this different naming come from?
Can I then remove one of the folders like in #1467 or do I have another problem due to the different naming?

When I call without oc_ I get two tables :

```
MariaDB [nextcloud]> SELECT * from bookmarks_root_folders WHERE user_id = 'ton';
+---------+-----------+
| user_id | folder_id |
+---------+-----------+
| ton     |         1 |
| ton     |         2 |
+---------+-----------+
2 rows in set (0.000 sec)
```

When I print the tables I see the names without oc_ Output :
```
MariaDB [nextcloud]> SHOW TABLES;
+----------------------------+
| Tables_in_nextcloud        |
+----------------------------+
| accounts                   |
| accounts_data              |
| activity                   |
| activity_mq                |
| addressbookchanges         |
| addressbooks               |
| appconfig                  |
| authtoken                  |
| bookmarks                  |
| bookmarks_folders          |
| bookmarks_folders_public   |
| bookmarks_root_folders     |
| bookmarks_shared_folders   |
| bookmarks_shared_to_shares |
| bookmarks_shares           |
| bookmarks_tags             |
| bookmarks_tree             |
| bruteforce_attempts        |
| calendar_invitations       |
| calendar_reminders         |
| calendar_resources         |
| calendar_resources_md      |
| calendar_rooms             |
| calendar_rooms_md          |
| calendarchanges            |
| calendarobjects            |
| calendarobjects_props      |
| calendars                  |
| calendarsubscriptions      |
| cards                      |
| cards_properties           |
| collres_accesscache        |
| collres_collections        |
| collres_resources          |
| comments                   |
| comments_read_markers      |
| dav_cal_proxy              |
| dav_shares                 |
| deck_assigned_labels       |
| deck_assigned_users        |
| deck_attachment            |
| deck_board_acl             |
| deck_boards                |
| deck_cards                 |
| deck_labels                |
| deck_stacks                |
| direct_edit                |
| directlink                 |
| federated_reshares         |
| file_locks                 |
| filecache                  |
| filecache_extended         |
| files_trash                |
| flow_checks                |
| flow_operations            |
| flow_operations_scope      |
| group_admin                |
| group_user                 |
| groups                     |
| jobs                       |
| login_flow_v2              |
| mail_accounts              |
| mail_aliases               |
| mail_attachments           |
| mail_classifiers           |
| mail_coll_addresses        |
| mail_mailboxes             |
| mail_messages              |
| mail_recipients            |
| mail_trusted_senders       |
| migrations                 |
| mimetypes                  |
| mounts                     |
| notifications              |
| notifications_pushtokens   |
| oauth2_access_tokens       |
| oauth2_clients             |
| preferences                |
| privacy_admins             |
| properties                 |
| recent_contact             |
| schedulingobjects          |
| share                      |
| share_external             |
| storages                   |
| storages_credentials       |
| systemtag                  |
| systemtag_group            |
| systemtag_object_mapping   |
| talk_attendees             |
| talk_bridges               |
| talk_commands              |
| talk_guestnames            |
| talk_internalsignaling     |
| talk_rooms                 |
| talk_sessions              |
| text_documents             |
| text_sessions              |
| text_steps                 |
| trusted_servers            |
| twofactor_backupcodes      |
| twofactor_providers        |
| user_status                |
| user_transfer_owner        |
| users                      |
| vcategory                  |
| vcategory_to_object        |
| webauthn                   |
| whats_new                  |
+----------------------------+
109 rows in set (0.001 sec)
```

**Comment by TonKkkkk** [comment] 2021-03-23 19:33
When I look in the folders, both are empty...
```
MariaDB [nextcloud]> SELECT * from bookmarks_root_folders WHERE user_id = 'ton';
+---------+-----------+
| user_id | folder_id |
+---------+-----------+
| ton     |         1 |
| ton     |         2 |
+---------+-----------+
2 rows in set (0.000 sec)
MariaDB [nextcloud]> SELECT * from bookmarks_tree WHERE parent_folder = 1;
Empty set (0.001 sec)

MariaDB [nextcloud]> SELECT * from bookmarks_tree WHERE parent_folder = 2;
Empty set (0.000 sec)
```

**Comment by Pinaute** [comment] 2021-03-23 20:06
I remove one of the folders and it works, no more blue page.
You can run the  command :
```sql
DELETE from bookmarks_root_folders WHERE user_id='ton' and folder_id=1;
```

**Comment by Pinaute** [comment] 2021-03-23 20:18
> Is this OK, where does this different naming come from?

I think so, this is normal.
The prefix has been removed here
https://github.com/nextcloud/server/pull/21112/files

**Comment by TonKkkkk** [comment] 2021-03-23 21:04
Thank you very much for the your support :1st_place_medal: 
This did the trick, works now as expected, see my bookmarks and are able to sync with Floccus

**Comment by marcelklehr** [comment] 2021-03-23 21:42
Cool! I'm glad it works now :)

Closing this as a duplicate of #1467

**Closed as completed by marcelklehr** 2021-03-23 21:42 UTC
Labels: bug, awaiting confirmation
