### ISSUE TITLE
Feature Request: Option to disable automatic fetching of remote metadata

### ISSUE THREAD

**Issue by johanpalmqvist** [nextcloud/bookmarks#692] opened 2019-04-26 19:21 UTC
As a bookmark hoarder I would like to disable creation of favicons and previews during sync of bookmarks to improve performance. Would be nice if it could be optionally disabled if not needed or fetched/created after successful sync as an optional maintenance job or on demand for frequently used bookmarks.

**Comment by marcelklehr** [comment] 2019-04-27 12:27
Duplicate of #647 ;)

**Closed as completed by marcelklehr** 2019-04-27 12:27 UTC
