### ISSUE TITLE
Organizing bookmarks in folders

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/bookmarks#557] opened 2018-08-30 05:04 UTC
I have about 100 bookmarks and synced them via floccus aut of my Firefox. In Firefox they are organized in folders. After syncing the hierachical folder names are used as tags. That's nice, but when I open the bookmarks, all bookmarks are presented and finding one is not easy. The tags are named with fierfox's full folder hierarchy:
- Level 1
  - Level 2
    - Level 3

is converted to
`floccus: > Level 1 > Level 2 > Level 3`

Depending on the name of a level, the following levels are not readable in the sidebar. It would be nice to have the levels hierarchically ordered in the side view and in the main view ordered in folders like i.e. in the gallery view.

**Comment by bernd-wechner** [comment] 2018-08-30 05:13
This is a duplicate of: https://github.com/nextcloud/bookmarks/issues/514

Go comment there and upvote that ;-).

**Closed as completed** 2018-08-30 05:19 UTC
Labels: duplicate
