### ISSUE TITLE
Could not extract app bookmarks

### ISSUE THREAD

**Issue by metbril** [nextcloud/bookmarks#1256] opened 2020-10-16 12:34 UTC
**Describe the bug**
When installing the Bookmarks app from my hosted Nextcloud, I get to see this error message

    Could not extract app bookmarks

(I have been able to succesfully install some other apps afterwards, just to test the appstore is working)

**To Reproduce**
1. Go to Settings, Apps gallery
2. Click 'download and install'
3. Error shown in yellow (see screenshot)

**Expected behavior**
Installation of the app.

**Screenshots**

<img width="243" alt="Schermafbeelding 2020-10-16 om 13 41 45" src="https://user-images.githubusercontent.com/559346/96258002-a7982880-0fbb-11eb-97e0-3dc797d46a5c.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]

**Server (please complete the following information):**
 - OS: ? using hosted cloud
 - HTTP server: ? using hosted cloud
 - Database: ? using hosted cloud
 - PHP version: ? using hosted cloud
 - Nextcloud version: 19.0.4
 - Bookmarks app version: latest?
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**
I have been googling and I found some similar errors that suggested a corrupted tar, or invalid signature.

**Web server error log**
```
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
{
  "reqId": "**removed**",
  "level": 3,
  "time": "2020-10-16T11:46:33+00:00",
  "remoteAddr": "**removed**",
  "user": "robert",
  "app": "settings",
  "method": "POST",
  "url": "/index.php/settings/apps/enable",
  "message": {
    "Exception": "Exception",
    "Message": "Could not extract app bookmarks",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 444,
        "function": "downloadApp",
        "class": "OC\\Installer",
        "type": "->",
        "args": [
          "bookmarks"
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 170,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->",
        "args": [
          [
            "bookmarks"
          ],
          []
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 100,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
          },
          "enableApps"
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/AppFramework/App.php",
        "line": 137,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
          },
          "enableApps"
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Settings\\Controller\\AppSettingsController",
          "enableApps",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "settings.AppSettings.enableApps"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "_route": "settings.AppSettings.enableApps"
          }
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/Route/Router.php",
        "line": 297,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "_route": "settings.AppSettings.enableApps"
          }
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/base.php",
        "line": 1011,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/settings/apps/enable"
        ]
      },
      {
        "file": "/var/www/vhosts/**removed**/httpdocs/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/vhosts/**removed**/httpdocs/nextcloud/lib/private/Installer.php",
    "Line": 295,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
  "version": "19.0.4.2",
  "id": "**removed**"
}
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by metbril** [comment] 2020-10-16 12:36
Related to #1052?

My issues is regarding a new installation of the app, not an update.

**Comment by metbril** [comment] 2020-10-16 12:45
My web host support has installed the app via OCC without issues, looks like the app store web interface is causing the issue.

**Comment by marcelklehr** [comment] 2020-10-16 15:12
@nextcloud/server-triage Any hints on why this might be happening?

**Comment by kesselb** [comment] 2020-10-16 16:30
https://github.com/nextcloud/server/issues/23482
https://github.com/nextcloud/server/issues/19674
https://github.com/nextcloud/server/issues/19061
https://github.com/nextcloud/deck/issues/2447
https://github.com/nextcloud/maps/issues/240

I don't think there is something to fix for app developers. A corrupted archive is something you could fix but that's not the case here as it works via occ. 

The library used to extract the archive is not very talkative why something failed. True or False is the response. The report at deck was fixed by increasing the temporary disk space available.

**Comment by marcelklehr** [comment] 2020-10-17 17:33
thanks @kesselb in this case I'll close this.

**Closed as completed by marcelklehr** 2020-10-17 17:33 UTC
Labels: bug

**Comment by brylie** [comment] 2020-10-21 11:44
What was the resolution of this issue? We are using a managed Nextcloud instance. Is there something that needs to be changed on the server?

**Comment by metbril** [comment] 2020-10-21 11:54
There is no real resolution. I have a kind hosting provider that installs or updates broken apps for me. So far I needed help with bookmarks and news so it isn't specific to 1 single app. 

It looks like the core team should ha e a look at this and provide more or better instructions how to release (updates to) apps that can be installed through the UI. 

First thing should be more talkative error handling that helps app maintainers to troubleshoot.

**Comment by brylie** [comment] 2020-10-22 10:16
@marcelklehr this may be a packaging-related issue. I got a support response from my Nextcloud hosting provider:

> I think the problem is in the package of this app and Nextcloud can't extract it.
> We had to pull it manually from their server and add it.
> This is rare, but it did already happen before when the developer didn't properly pack the app.

Would you please consider re-opening this issue, so we can determine whether it is caused by the packaging setup?

**Comment by marcelklehr** [comment] 2020-10-22 11:14
> I think the problem is in the package of this app and Nextcloud can't extract it.

The fact that some instances are able to install this (including my own prod instance) would disprove that theory.

**Comment by metbril** [comment] 2020-10-22 17:00
@brylie see my comment https://github.com/nextcloud/bookmarks/issues/1052#issuecomment-712230676 

The issue also occurs for the `news` app.

**Comment by kesselb** [comment] 2020-10-22 17:14
Your hosting company can apply https://github.com/nextcloud/server/pull/23608/files to have more details why extract fails. At least for install. To provide this information on app update (to the end user) is a bit more work. Administrators see the error response from the archive library also in the logs (with the above patch applied).

**Comment by brylie** [comment] 2020-10-23 07:46
Thanks @kesselb. I will pass this on to our hosting company.

By the way, do we have any error logs related to the bookmarks app install failures?

I just tried upgrading to the 4.0 release, but got the same error. It would be good to know where the issue resides, e.g. if it is with packaging or something with Nextcloud.

**Comment by brylie** [comment] 2020-10-23 07:51
> The fact that some instances are able to install this (including my own prod instance) would disprove that theory.

It would be interesting to know the differences in **environment** with the success cases versus the failures. E.g. is this related to a PHP version/series? Is there a difference in versions of server components, such as PEAR libraries? Is package size a factor in some environments?

What is the packaging process for the bookmarks app? Are there similarities between the bookmarks and news app that might point to a common issue?

**Comment by metbril** [comment] 2020-10-28 13:01
This is some of my system's information:

<img width="253" alt="Schermafbeelding 2020-10-28 om 14 00 37" src="https://user-images.githubusercontent.com/559346/97439058-fdf35880-1925-11eb-96f0-45345681cc06.png">

<img width="338" alt="Schermafbeelding 2020-10-28 om 13 51 42" src="https://user-images.githubusercontent.com/559346/97438248-d5b72a00-1924-11eb-827e-12e888d88546.png">

<img width="562" alt="Schermafbeelding 2020-10-28 om 13 52 53" src="https://user-images.githubusercontent.com/559346/97438305-e8c9fa00-1924-11eb-95d0-5ba15a32ea9d.png">

<img width="562" alt="Schermafbeelding 2020-10-28 om 13 53 22" src="https://user-images.githubusercontent.com/559346/97438353-fb443380-1924-11eb-8f9d-3e388c19833e.png">

And this is the logging from trying the update from 3.4.4 to 3.4.6.

```
[core] Error: Exception: Could not extract app bookmarks at <<closure>>

0. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/Installer.php line 197
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. /var/www/vhosts/**masked**/httpdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 531
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
4. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
5. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. /var/www/vhosts/**masked**/httpdocs/nextcloud/lib/base.php line 1011
   OC\Route\Router->match("/settings/apps/update/bookmarks")
9. /var/www/vhosts/**masked**/httpdocs/nextcloud/index.php line 37
   OC::handleRequest()

GET /settings/apps/update/bookmarks
from **masked** by **masked** at 2020-10-28T12:55:20+00:00
```

BTW. Since we're still discussing this issue, wouldn't it be wise to have @marcelklehr reopen it to prevent duplicates?

**Comment by metbril** [comment] 2020-11-11 06:26
I'm not sure what has changed in the extension package but yesterday I was able to upgrade from 3.4.6 to 3.4.9 without issues. I will watch future updates and report back.
