### ISSUE TITLE
Edit bookmark name in Details Menu

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#973] opened 2020-04-16 19:01 UTC
![Screenshot_20200416_115828](https://user-images.githubusercontent.com/1787238/79495544-9acd5480-7fd9-11ea-9499-aca2f9aeaef1.png)

I'd like to be able to edit the bookmark's title displayed just above the URL from within Details Menu.
This would allow the title to change from  `RCA-BNC adapter` to anything: `Turntable RCA-BNC adapter`.  No big deal, but thanks for considering

**Comment by SuperSandro2000** [comment] 2020-04-16 21:00
Dupe of #875, closed in https://github.com/nextcloud/bookmarks/commit/93e2df6f923a62b778f2b0589cdd666b78e51c12 and will be in 3.0.0.

**Comment by sunjam** [comment] 2020-04-16 21:04
@SuperSandro2000 that is for editing urls, not the **title**.  I'd like to edit the title.  Tested 3.0.0-1 beta and this is not possible afaik.

**Comment by marcelklehr** [comment] 2020-04-22 15:16
Editing the title is possible from the three-dot-menu directly on the bookmark, but it's probably better to have it in the sidebar.

**Closed as completed** 2020-09-14 08:45 UTC
Labels: good first issue
