### ISSUE TITLE
Import of duplicate bookmarks messes up tags

### ISSUE THREAD

**Issue by mkaehlcke** [nextcloud/bookmarks#326] opened 2017-01-03 05:32 UTC
1. Import a bookmark file
2. Import the same bookmark file again

### Expected behaviour
Ideally: Bookmarks remain unchanged
Second best: Bookmarks are duplicated, tags are correct

### Actual behaviour
Bookmarks are duplicated and the tags of some of the bookmarks don't match the content of the file (eg. bookmark 1 has tags of bookmark 11, bookmark 2 of bookmark 12, ...)

### Additional information

The following bookmark file can be used to reproduce the problem:

[bm_20.html.txt](https://github.com/nextcloud/bookmarks/files/681707/bm_20.html.txt)

### Server configuration
**Operating system:**  Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.16

**PHP version:** 7.0.8

**Nextcloud version:** 11.0

**Bookmarks version:** 0.9.1

**Updated from an older Nextcloud or fresh install:** latest Nextcloud appliance (updates itself?)

**Where did you install Nextcloud from:** Nextcloud appliance

**Comment by 4oo4** [comment] 2017-07-02 22:33
This sounds similar to an issue I'm having when I accidentally enter a duplicate bookmark. When I do that, it pulls the duplicate entry to the top of the list (as expected), but then it will turn every character in the tag into a new tag. For example, if the entry was tagged "Javascript", it would then change it to "J a v a s c r i p t", turning one tag into 10 tags. However, when you reload the page it reverts back to the correct tag.

Install/system info here: https://github.com/nextcloud/bookmarks/issues/389

No errors in access logs, nextcloud.log, the only thing in dev tools was about Synchronous XHR:
```
core.js?v=fedb76e…-0:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check **https://xhr.spec.whatwg.org/.
```

**Comment by blizzz** [comment] 2017-07-16 15:52
Not sure whether it's the #390 fix (I rather think it were other PRs merged recently), however I cannot reproduce the faulty the behaviour. Thus I appears to be fixed inbetween → closing. 

@mkaehlcke If you still encounter the issue, please reopen.

**Closed by blizzz** 2017-07-16 15:52 UTC
Labels: awaiting confirmation, bug, import
