### ISSUE TITLE
[Feature request] Add option to disable backup

### ISSUE THREAD

**Issue by zevlee** [nextcloud/bookmarks#1781] opened 2022-04-01 07:35 UTC
Please add a way to disable the bookmarks backup feature. For users who regularly back up their entire Nextcloud server, the bookmarks backup is redundant.

### Discussed in https://github.com/nextcloud/bookmarks/discussions/1778

<div type='discussions-op-text'>

<sup>Originally posted by **zevlee** March 29, 2022</sup>
Is there a way to disable Bookmarks Backups to Files? I do not find an option to do so.

I use Nextcloud Bookmarks with Floccus, so my bookmarks are saved already in my browser.</div>

**Comment by mepreston** [comment] 2022-04-03 19:11
don't be generating files on my nextcloud system automatically without giving me an option do disable said automation.  this is lazy.

**Comment by marcelklehr** [comment] 2022-04-04 12:46
@mepreston Please be respectful. Calling people names that work in their free time to provide software for free is not cool.

**Comment by mayswind** [comment] 2022-04-04 15:08
@marcelklehr I have always thought this app is good, and used it for years, until it does backup job without user's permission. At least for me, the backup files this app creates are junk files. I think this app should not do anything in my file system before I authorize it. By the way, if you do well, users can praise your work, but if you do not do well, users have the right to criticize you, whether it is provided to users for free or not.

**Comment by marcelklehr** [comment] 2022-04-04 16:42
> By the way, if you do well, users can praise your work, but if you do not do well, users have the right to criticize you, whether it is provided to users for free or not.

Thank you. I happen to agree. However, there is a difference between constructive criticism and calling people names, and since I am maintaining this software I have the right to call people out that are disrespectful. Someone calls me lazy, I call them out on it and insist on respectful manners. That's it.

**Comment by Andandaran** [comment] 2022-04-08 08:23
> don't be generating files on my nextcloud system automatically without giving me an option do disable

I totally agree with that. I was scared when I saw a directory and a bunch of files inside my nexcloud instance. First impression was: Someone has hacked my system !!!

I have the plugin disabled until there is an option to disable backups.

Thank you for your work, but please add some option to disable backups. And probably there should be options to set the retention if someone want/need the backups (not my case).

**Comment by zevlee** [comment] 2022-04-08 20:33
> I was scared when I saw a directory and a bunch of files inside my nexcloud instance. First impression was: Someone has hacked my system !!!

I had the same concern. I think this issue illustrates a potential need for a permission system for nextcloud apps, where privileges like file system access must be requested and then explicitly granted by individual users.

**Comment by marcelklehr** [comment] 2022-04-11 18:24
Duplicate of #1791 1779

**Closed as completed by marcelklehr** 2022-04-11 18:24 UTC

**Comment by marcelklehr** [comment] 2022-06-09 11:55
fyi v10.4.0 defaults to backups off for all users
