### ISSUE TITLE
[Suggestion] Add list view

### ISSUE THREAD

**Issue by untilbit** [nextcloud/bookmarks#561] opened 2018-09-08 15:31 UTC
Add a list view with the option to select bookamrks, name, taks and options

**Comment by LordVanguard** [comment] 2018-09-09 16:10
+1      

Truth be told the thumbnail view with the plethora of bookmarks I have makes browsing/syncing a little slow. My nextcloud instance syncs for ages. A simplified nested list (even if just a text based YAML style indent) would be fantastic. 

Great project, its something that I find hard to believe hasnt become a standard thing in modern browsers given the number of devices we use these days. Keep it up :+1:

**Comment by marcelklehr** [comment] 2018-09-20 00:51
This is a duplicate of #552 ;)

**Closed as completed by marcelklehr** 2018-09-20 00:51 UTC
