### ISSUE TITLE
Credentials for Private RSS Feed of Current View

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1236] opened 2020-10-03 16:14 UTC
NextcloudPi 19.0.3 with Bookmarks 3.4.1

**Is your feature request related to a problem? Please describe.**
I'm asked to supply credentials when first accessing the RSS url from Nextcloud, as opposed to supplying credentials to the RSS application directly.

**Describe the solution you'd like**
- Copy Private Feed RSS url in Nextcloud
- Add to an RSS application, along with username and password credentials.

**Additional context**
This is totally amazing!  Haven't gotten it to work, but it is amazing.

401 unauthorized when pasting the Private RSS Feed for current view.
Fails when adding credentials.  Fails when adding credentials and one time password.

**Comment by marcelklehr** [comment] 2020-10-03 17:51
mmh, are you using LDAP or a different user backend?

**Comment by sunjam** [comment] 2020-10-03 18:03
Nope

**Comment by marcelklehr** [comment] 2020-10-03 18:48
Oh, so when supplying credentials in the browser, the feed is displayed and this is about the usability issue?

**Comment by sunjam** [comment] 2020-10-03 18:54
> Oh, so when supplying credentials in the browser, the feed is displayed and this is about the usability issue?

Usability, but the feed also fails in Nextcloud News with a 401 unauthorized user after being added.

I'm attempted to add:
1. Private Feed url
2. Private Feed url with username and password
3. Private Feed url with username and one-time password

All of them fail.

**Comment by marcelklehr** [comment] 2020-10-03 19:10
The latter is a duplicate of https://github.com/nextcloud/bookmarks/issues/755 -- nothing has changed on this front, IMHO

**Closed as completed** 2021-04-13 12:29 UTC
