### ISSUE TITLE
Missing column error

### ISSUE THREAD

**Issue by JevgenySkorik** [nextcloud/bookmarks#1130] opened 2020-07-29 07:15 UTC
**Describe the bug**
After upgrading a server to version 18.0.7 we started getting an error when trying to execute occ commands.
With the bookmarks app disabled the problem doesn't occur, but everytime we try to enable the app again we get the same error.

**Error:**
An exception occurred while executing 'DELETE FROM `oc_bookmarks_shared_folders` WHERE (`id` = ?) AND (`type` = ?)' with params ["92", "share"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'

**Server:**
 - OS: Ubuntu 18.04
 - HTTP server: nginx
 - Database: MySQL 5.3
 - PHP version: 7.3
 - Nextcloud version: 18.0.7
 - Activated Nextcloud Apps: https://pastebin.com/X32nrL6f
 - Nextcloud configuration: https://pastebin.com/856v2Cbf

**Comment by marcelklehr** [comment] 2020-07-29 09:15
This is a duplicate of #1127 and is fixed in v3.3.2

**Closed as completed by marcelklehr** 2020-07-29 09:15 UTC
Labels: bug

**Comment by JevgenySkorik** [comment] 2020-07-29 09:41
When trying to update or install the app there is a new error. This is the output of "sudo -u www-data php occ app:install bookmarks" after removing the app:

An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Activity\Event::setAuthor() must be of the type string, null given, called in /var/www/nextcloud/apps/bookmarks/lib/Activity/ActivityPublisher.php on line 96 and defined in /var/www/nextcloud/lib/private/Activity/Event.php:166
Stack trace:
#0 /var/www/nextcloud/apps/bookmarks/lib/Activity/ActivityPublisher.php(96): OC\Activity\Event->setAuthor(NULL)
#1 /var/www/nextcloud/apps/bookmarks/lib/Activity/ActivityPublisher.php(86): OCA\Bookmarks\Activity\ActivityPublisher->publishShare(Object(OCA\Bookmarks\Events\CreateEvent))
#2 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(76): OCA\Bookmarks\Activity\ActivityPublisher->handle(Object(OCA\Bookmarks\Events\CreateEvent))
#3 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(247): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCA\Bookmarks\Events\CreateEvent), 'OCA\\Bookmarks\\E...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCA\\Bookmarks\\E...', Object(OCA\Bookmarks\Events\CreateEvent))
#5 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(80): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCA\Bookmarks\Events\CreateEvent), 'OCA\\Bookmarks\\E...')
#6 /var/www/nextcloud/apps/bookmarks/lib/Db/SharedFolderMapper.php(221): OC\EventDispatcher\EventDispatcher->dispatch('OCA\\Bookmarks\\E...', Object(OCA\Bookmarks\Events\CreateEvent))
#7 /var/www/nextcloud/apps/bookmarks/lib/Service/FolderService.php(354): OCA\Bookmarks\Db\SharedFolderMapper->mount(109, 6)
#8 /var/www/nextcloud/apps/bookmarks/lib/Migration/GroupSharesUpdateRepairStep.php(123): OCA\Bookmarks\Service\FolderService->addSharedFolder(Object(OCA\Bookmarks\Db\Share), Object(OCA\Bookmarks\Db\Folder), 'Ruslan Muradymo...')
#9 /var/www/nextcloud/lib/private/Repair.php(104): OCA\Bookmarks\Migration\GroupSharesUpdateRepairStep->run(Object(OC\Repair))
#10 /var/www/nextcloud/lib/private/legacy/app.php(981): OC\Repair->run()
#11 /var/www/nextcloud/lib/private/Installer.php(160): OC_App::executeRepairSteps('bookmarks', Array)
#12 /var/www/nextcloud/core/Command/App/Install.php(66): OC\Installer->installApp('bookmarks')
#13 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#19 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#20 {main}

**Comment by marcelklehr** [comment] 2020-07-30 18:32
Aaand fixed in v3.3.3
