### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by exekutive** [nextcloud/bookmarks#494] opened 2018-05-25 18:48 UTC
Fairly self explanatory. I'm surprised nobody suggested it yet.

**Comment by marcelklehr** [comment] 2018-05-25 19:31
duplicate of #32 #64 #297 ;)

**Closed as completed by marcelklehr** 2018-05-25 19:31 UTC

**Comment by exekutive** [comment] 2018-05-26 00:45
Sorry, I guess I should have searched closed issues as well.

**Comment by marcelklehr** [comment] 2018-05-26 12:02
No problem :D

**Comment by damko** [comment] 2018-05-30 09:27
@exekutive as a temporary solution you can use my Firefox [addon](https://addons.mozilla.org/en-US/firefox/addon/freedommarks/) for searching bookmarks
