### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS from XMLHttpRequests

### ISSUE THREAD

**Issue by martinjakl** [nextcloud/bookmarks#329] opened 2017-01-12 17:44 UTC
Hello,
i'm author of this chrome extension https://chrome.google.com/webstore/detail/owncloud-bookmarks/eomolhpeokmbnincelpkagpapjpeeckc?utm_source=chrome-ntp-icon and I'm trying to adjust it for current owncloud/nextcloud. I've understood that now the call to get all bookmarks with tags should be something like /nextcloud/index.php/apps/bookmarks/public/rest/v1/bookmark?select=tags&user=user&password=pw but if I use it I'm getting net::ERR_TOO_MANY_REDIRECTS. Is this connected to higher security nextcloud has? How to use it properly?

**Comment by blizzz** [comment] 2017-02-05 17:35
Hi @martinjakl, thanks for your report.

For me it sounds either like a web server misconfiguration (not so likely) or indeed something wrong with the app. Perhaps authentication does not work? Or the app is disabled? Although, this should lead to one redirect, not too many.

I would like to prepare for some changes for the next release. Especially we will get rid of sending the password as GET parameter…

**Comment by martinjakl** [comment] 2017-02-06 17:29
I have it installed from openSUSE repository. Problem is that the same request works when done from browser's address bar or curl. It does this infinite redirect only when requested from XMLHttpRequests. It looks like that it's some CORS protection in nextcloud 11. I've checked bookmarks extension sourcecode and it seems be in controller/rest/publiccontroler.php and function there is marked with @CORS, but it somehow doesn't work.

**Comment by blizzz** [comment] 2017-02-15 12:11
Hm. Which bookmarks version are we talking about?

**Comment by martinjakl** [comment] 2017-02-15 12:23
0.9.1

**Comment by blizzz** [comment] 2017-02-15 13:49
Could you try whether it works with commits https://github.com/nextcloud/bookmarks/pull/328/commits/0487c2be0de3c7ba5ff1e0c396e41c3b79f4abc9 and https://github.com/nextcloud/bookmarks/pull/328/commits/8d00429ac16e832b82b9937481f9a896415269d6 (from #328)?

**Comment by martinjakl** [comment] 2017-02-15 15:39
It doesn't seem to help.

**Comment by brantje** [comment] 2017-02-16 01:23
@martinjakl I've had this problem too when developing the passman extension.
Turns out you have to use `fetch(url)` [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)

**Comment by martinjakl** [comment] 2017-02-16 17:29
That works, thanks!

**Comment by blizzz** [comment] 2017-02-18 22:35
Cool you got a solution. I understand the issue is not within Bookmark code → closing.

**Closed by blizzz** 2017-02-18 22:35 UTC
