### ISSUE TITLE
Feature Request: Search for exact tags ...

### ISSUE THREAD

**Issue by ddeimeke** [nextcloud/bookmarks#593] opened 2018-11-11 12:38 UTC
Search for the tag "cli" also finds "eclipse". It would be nice to do an exact search .

**Comment by marcelklehr** [comment] 2018-11-11 17:02
Duplicate of https://github.com/nextcloud/bookmarks/issues/515 which admittedly had an obfuscated title. :)

**Closed as completed by marcelklehr** 2018-11-11 17:02 UTC
