### ISSUE TITLE
RFE: ability to share bookmarks

### ISSUE THREAD

**Issue by nursoda** [nextcloud/bookmarks#355] opened 2017-05-15 03:55 UTC
I need to share bookmarks with other NC users.

**Comment by blizzz** [comment] 2017-05-15 12:08
Duplicate of https://github.com/nextcloud/bookmarks/issues/5

**Closed as completed by blizzz** 2017-05-15 12:08 UTC

**Comment by nursoda** [comment] 2017-05-15 12:45
I am very sorry!

(I did search but was blind. I searched for "share" which doesn't match "sharing".)

**Comment by blizzz** [comment] 2017-05-15 19:30
no problem :)
