### ISSUE TITLE
FR: Dark theme support

### ISSUE THREAD

**Issue by gerroon** [nextcloud/bookmarks#646] opened 2019-01-25 00:03 UTC
Hi

It would be very nice if this app respectecs the dark theme. With the dark theme, everything except this apps content is  dark. It makes it hard to look and browse bookmarks while the dark theme is enabled.

thanks

**Comment by marcelklehr** [comment] 2019-02-05 18:40
Hey there, thanks for yoru feedback! This is a duplicate of https://github.com/nextcloud/bookmarks/issues/596, however, feel free to comment over there :)

**Closed as completed by marcelklehr** 2019-02-05 18:40 UTC
