### ISSUE TITLE
Import error on Firefox: Permission denied to access property "apply"

### ISSUE THREAD

**Issue by nkorth** [nextcloud/bookmarks#689] opened 2019-04-23 16:35 UTC
### Steps to reproduce
1. Click "Import" button

### Expected behaviour
Something happens when I click the button

### Actual behaviour
Nothing happens because this error is thrown:
```
Error: Permission denied to access property "apply" [Learn More] main.bundle.js:11989:4
    trigger https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:11989
    trigger https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:12062
    each https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:4089
    each https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:3924
    trigger https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:12061
    name https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:13947
    importTrigger https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:34023
    executeBound https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:2759
    bound https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:2772
    restArguments https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:2119
    dispatch https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:8917
    handle https://nkorth.com/nextcloud/custom_apps/bookmarks/js/dist/main.bundle.js?v=5945a740-2:8726
```

Here's the ["learn more" link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default). Looks like maybe Firefox doesn't like programmatically clicking on file inputs?

### Server configuration
**OS/Webserver:** official docker image on ubuntu

**Nextcloud version:** 14.0.6

**Bookmarks version:** 0.17.0

**Updated from an older Nextcloud or fresh install:** Upgraded from 13

**Signing status:** No errors have been found.

**List of activated apps:**
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - apporder: 0.6.0
  - bookmarks: 0.17.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.1
  - drawio: 0.9.2
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - keeweb: 0.5.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - news: 13.0.3
  - nextcloud_announcements: 1.3.0
  - notes: 2.6.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
```

**Nextcloud configuration:** probably not relevant, can provide if needed

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 66.0.2

**Operating system:** OS X 10.14.2

**Comment by nkorth** [comment] 2019-04-23 18:25
Tried it in Safari and it works, so this is definitely an issue with Firefox compatibility.

**Comment by marcelklehr** [comment] 2019-04-25 20:22
Mh, I cannot reproduce this in Firefox 66.0.3

**Comment by marcelklehr** [comment] 2019-04-25 20:25
It could be that this is caused by an addon that you have installed.

**Comment by nkorth** [comment] 2019-04-25 21:15
Strange, the problem stopped happening without any change to my addons or Firefox version. I was consistently able to repro it several times the other day. The only change is that I have some bookmarks in the app now, but that wouldn't make any sense as the cause, right?

**Comment by marcelklehr** [comment] 2019-04-25 21:30
> but that wouldn't make any sense as the cause, right?

No, I also didn't have any in my test instance when I tried to reproduce. Perhaps your firefox got updated? In any case I'm closing this :tada:

**Closed as completed by marcelklehr** 2019-04-25 21:30 UTC
Labels: awaiting confirmation
