### ISSUE TITLE
bookmark incompatible with 28 version

### ISSUE THREAD

**Issue by stanthewizzard** [nextcloud/bookmarks#2106] opened 2023-12-12 20:41 UTC
hello

endless log

`"reqId":"XMexpPCiZdKOskDRV8SR","level":3,"time":"2023-12-12T20:39:32+00:00","remoteAddr":"192.168.0.30","user":"stan","app":"no app in context","method":"POST","url":"/settings/apps/disable","message":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":146,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":173,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":443,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":64,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":56,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"function":"OC\\AppFramework\\Bootstrap\\{closure}","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":45,"function":"array_map"},{"file":"/app/www/public/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/config/www/nextcloud/apps/bookmarks/lib/AppInfo/Application.php","line":104,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\Bookmarks\\AppInfo\\Application","type":"->"},{"file":"/app/www/public/lib/private/App/AppManager.php","line":434,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/app/www/public/lib/private/App/AppManager.php","line":213,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_App.php","line":125,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/app/www/public/lib/base.php","line":1049,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/app/www/public/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":135,"message":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","exception":{},"CustomMessage":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist"}}`

**Comment by EiTiFuzzi** [comment] 2023-12-13 08:25
I have the same problem. I look forward to a quick solution.

**Comment by joshtrichards** [comment] 2023-12-13 16:13
Duplicate of #2102

**Closed as not planned by joshtrichards** 2023-12-13 16:13 UTC
Labels: bug
