### ISSUE TITLE
Use existing/global/collaborative tags instead of own.

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/bookmarks#1512] opened 2021-04-21 18:13 UTC
**Is your feature request related to a problem? Please describe.**
It's an enhancement to improve compatibility with other apps (collaborative tags/shared tags across all users) and for convenience.

**Describe the solution you'd like**
Usage of the same tagging system as for other apps/files.
Usage of existing tags (from ex. files).
This adds the ability to easily rename any tag (at least with the collaborative tags app). 
[edit.: Thinking about that, I don't know about the tagging system without this app anymore… Maybe I should name this issue "Add compatibility with the collaborative tags app"?]

**Describe alternatives you've considered**
I haven't (yet) and I don't think there are.

**Additional context**
It simply seems to be off when having different tags/tag-scheme within the same ecosystem and be it only the difference between uppercase and lowercase as the first letter.
Additionally, it helps to collaborate when everyone uses the same tags or naming scheme. 

PS: Now I'm done. It's late and I'll make some dinner :)

**Comment by marcelklehr** [comment] 2021-04-22 09:39
This is a duplicate of #794 -- Thanks for the feedback in any case :)

**Closed as completed by marcelklehr** 2021-04-22 09:39 UTC
