### ISSUE TITLE
Moving bookmark from root to folder keeps bookmark in root folder

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#772] opened 2019-08-16 08:35 UTC
### Steps to reproduce
1. Create a new bookmark for http://example.com/
2. Create a new folder 'Test'
3. Drag the bookmark from step 1 into folder Test

### Expected behaviour
The bookmark should be in the Test folder, and only in the Test folder.

### Actual behaviour
The bookmark is shown in the Test folder, but is also still in the 'root' folder, as seen from the database:
```
MariaDB [nextcloud]> select * from oc_bookmarks where url='http://example.com/';
+----+---------------------+----------------+---------+-------------+--------+------------+--------------+------------+--------------+
| id | url                 | title          | user_id | description | public | added      | lastmodified | clickcount | last_preview |
+----+---------------------+----------------+---------+-------------+--------+------------+--------------+------------+--------------+
| 49 | http://example.com/ | Example Domain | gmc     |             |      0 | 1565944145 |   1565944153 |          0 |            0 |
+----+---------------------+----------------+---------+-------------+--------+------------+--------------+------------+--------------+
1 row in set (0.01 sec)

MariaDB [nextcloud]> select * from oc_bookmarks_folders_bookmarks where bookmark_id=49;
+-----------+-------------+-------+
| folder_id | bookmark_id | index |
+-----------+-------------+-------+
|        -1 |          49 |    41 |
|         7 |          49 |     2 |
+-----------+-------------+-------+
2 rows in set (0.00 sec)

MariaDB [nextcloud]> 
```

## Server configuration detail

**Operating system:** Linux 4.14.133-166 #1 SMP PREEMPT Mon Aug 5 22:49:45 -03 2019 armv7l

**Webserver:** nginx/1.17.2 (fpm-fcgi)

**Database:** mysql 10.0.38

**PHP version:** 

7.3.8
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - bookmarks: 1.1.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.1
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "example.com",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/www.example.com",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "app_install_overwrite": [
        "calendar"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
n/a
```
</details>

<details><summary>Nextcloud log</summary>

```
n/a
```
</details>

<details><summary>Browser log</summary>

n/a
</details>

**Comment by sonologic** [comment] 2019-08-16 08:40
I realize this maybe is 'as designed', if that is the case, it would be nice to be able to see in the web ui which bookmarks are not in a subfolder, but only in the root folder.

**Comment by marcelklehr** [comment] 2019-09-11 12:53
This is not by design. It should be fixed in the upcoming version of the UI

**Closed as completed by marcelklehr** 2019-09-11 12:53 UTC
