### ISSUE TITLE
Native bookmarks synchronization

### ISSUE THREAD

**Issue by craigarno** [nextcloud/bookmarks#14] opened 2013-04-26 16:47 UTC
I also really liked this proposal by "DeliveryBoy" http://forum.owncloud.org/viewtopic.php?f=4&t=9808 which might go halfway toward solving #13 for me.  How close is this request to #2 and #5?

Summary:
I would appreciate to have an Extension, an Add-On or a Plug-In respectively; (whatever it is called for any browser) for automatically synchronizing my browser's native bookmarks with ownCloud. The idea is to have something like that for any major browsers like e.g. Safari, Firefox, Chrome, Opera and of course Internet Explorer — Are there any plans for developing such a piece of software?

I just stumbled over this existing software @ http://canisbos.com/cloudmarks — It does exactly what I want except it doesn't support ownCloud.

**Comment by Frenzie** [comment] 2016-05-01 06:04
Note that several browsers (most notably Firefox) also have keywords, which allow you to easily access your favorite sites. It'd be nice to have them in addition to tags and folders.

**Comment by marcelklehr** [comment] 2017-05-14 08:40
The Floccus webextension now works as intended to provide native bookmark syncronization: https://github.com/marcelklehr/floccus ;)

**Comment by samweisgamdschie** [comment] 2017-09-11 09:23
From a Users sight it's very hard to have no sync for browser information like bookmarks (history, open tabs, logins, etc) any more. 

It would be so pretty helpful if at least bookmark sync between all my firefox installations work. But when I think of having all my folder structures replaced with tags and a flat hierarchy, and further having most of my bookmarks multiplicated, it would not be an option for me.

Please please please add folder structure and additional metadata information like keywords! I guess you will win so many new users for your app just because of the ability to have seamless browser sync!

**Comment by craigarno** [comment] 2017-09-11 09:59
If your requirement is to be able to use OwnCloud Sync, Pale Moon still
supports Sync 1.1.  Pale Moon is a maintained branch off Firefox around
v28.  The Pale Moon site also has the server side Sync setup, so if
you've lost keys and such, they can be regenerated, just like you did
when Mozilla supported Sync 1.1.

I froze my Firefox installation at 53.03 as the last which will work
with an existing Sync 1.1/OwnCloud installation.  I use Pale Moon for
everything except video sites.  Pale Moon Sync 1.1 also works on my new
Android phone.  So, here is a solution which works, for me at least.

**Comment by shtrom** [comment] 2017-12-20 04:10
There is a WebExtensions addon that looks decent https://github.com/damko/freedommarks-browser-webextension

**Comment by marcelklehr** [comment] 2018-03-19 23:31
FYI, Floccus supports custom folders (even the browser root folder) and folder hierarchies now. :)

**Comment by sunjam** [comment] 2018-04-02 19:07
Hey, what steps are left to achieve full native synchronization via Nextcloud Bookmarks?  Seems that at least some of this issue is resolved.

[FreedomMarks extension is claiming compatibility with Opera, Safari and Microsoft Edge/Internet Explorer](https://github.com/damko/freedommarks-browser-webextension).  Waiting for instructions from @damko on how to install and test.

**Comment by marcelklehr** [comment] 2018-07-16 19:29
> I would appreciate to have an Extension, an Add-On or a Plug-In respectively;[...]for automatically synchronizing my browser's native bookmarks with ownCloud.

1. This was kind of out of scope of this project to begin with.
2. Now, that there is a viable API available, it's possible to realize this.
3. There is at least one extension available that claims to do what was requested and is actively developed. ( https://github.com/marcelklehr/floccus )

Feel free to continue the discussion, but I'll close this issue for now. :)

**Closed by marcelklehr** 2018-07-16 19:29 UTC
Labels: enhancement
