### ISSUE TITLE
Feature Request: Organize bookmarks into folders

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/bookmarks#519] opened 2018-06-28 02:11 UTC
Bookmarks in a browser (at least Firefox and Chrome) are thus organised, into folders and [floccus](https://github.com/marcelklehr/floccus) is a brilliant tool that syncs browser bookmarks with this NextCloud Bookmarks app. Alas it flattens the whole folder tree that a bookmark is in into a tag. So if I have a bookmark to this Github project filed as:

- Toolbar
    - GitHub
        - NextCloud
            - Bookmarks

floccus will save it as a bookmark with a single tag `floccus:Toolbar>GitHub>NextCloud>Bookmarks`.

I would be nice if this app offered a folder hierarchy as well that helps regardless when manageing large collections of any sort.

**Comment by marcelklehr** [comment] 2018-07-17 21:47
hey bernd :)
this is a duplicate of #514 -- feel free to comment over there ;)

**Closed as completed by marcelklehr** 2018-07-17 21:47 UTC
