### ISSUE TITLE
Access Bookmarks app from within other Nextcloud Apps (such as Notes or Rainloop or Activity)

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#393] opened 2017-07-13 04:03 UTC
I would love to be able to access my bookmarks from within other Nextcloud applications by url, title, description or tags.  Conversely, it would be great if I could add urls in other Nextcloud applications and have them auto-populate to the Bookmarks application as well.

**Comment by blizzz** [comment] 2017-07-14 19:43
There's not a dedicated PHP API. The Rest one builds around the Bookmarks class (``OCA\Bookmarks\Controller\Lib\Bookmarks``). In your app you could try to check whether the bookmarks app is enabled and if so query the server container for this specific class. For now at least, it's not guaranteed to be stable. Or perhaps ``OCA\Bookmarks\Controller\Rest\BookmarkController`` which would be the Rest API, not sure whether this works though.

**Comment by marcelklehr** [comment] 2017-08-24 15:34
Duplicate of #215

**Closed as completed by marcelklehr** 2017-08-24 15:34 UTC
