### ISSUE TITLE
cannot update from 4.0.2 to 4.0.4

### ISSUE THREAD

**Issue by ratermir** [nextcloud/bookmarks#1307] opened 2020-11-04 12:21 UTC
During attempt to update from 4.0.2 to 4.0.4 I got message "Error during application update. Update cannot continue. Application was not updated" (I translated the message from czech language so it may not be accurate).

I looked into NC log, but I haven't found anything suspicious nor relating to the app update.

I repeated this attempt several times, also after restart the whole NC environment (all relating docker containers - NC, redis, MariaDB, nginx) - the result is still the same, and no log message.

NC 20.0.0 docker version, php FPM 
database MariaDB 
hosting OS: Debian 10 (16GB mem,

**Comment by marcelklehr** [comment] 2020-11-04 12:32
Duplicate of #1306

**Closed as completed by marcelklehr** 2020-11-04 12:32 UTC
Labels: bug
