### ISSUE TITLE
Internal Server Error (NC28)

### ISSUE THREAD

**Issue by taschenlampe** [nextcloud/bookmarks#2104] opened 2023-12-09 15:43 UTC
Hi there!

I want to report that the bookmark plugin does not load, in NC is see:
Internal server error

**To Reproduce**
Open the plugin in NC

**Desktop (please complete the following information):**
 - OS: OpenSuse TW
 - Browser: Firefox
 - Version: 120

**Server (please complete the following information):**
 - OS: ubuntu 22.04
 - HTTP server: nginx version: nginx/1.25.3
 - Database: mysql  Ver 15.1 Distrib 10.6.12-MariaDB
 - PHP version: Copyright (c) The PHP Group/Zend Engine v4.1.25, Copyright (c) Zend Technologies   with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies
 - Nextcloud version: 28RC
 - Bookmarks app version: 13.1.1
 - Activated Nextcloud Apps: Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bookmarks: 13.1.1
  - breezedark: 27.0.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0-rc.2
  - contactsinteraction: 1.9.0
  - cospend: 1.5.12
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0-beta.4
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - integration_openai: 1.1.5
  - keeweb: 0.6.13
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - music: 1.9.1
  - news: 25.0.0-alpha2
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0-beta.1
  - richdocumentscode: 23.5.602
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - spreed: 18.0.0-rc.3
  - support: 1.11.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - audioplayer: 3.4.0 (installed 3.4.0)
  - circles: 28.0.0-dev (installed 25.0.0)
  - documentserver_community: 0.1.13 (installed 0.1.13)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.9.0)
  - libresign: 7.1.1 (installed 7.1.1)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)
 - Nextcloud configuration: 
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmd64337.contaboserver.net",
            "luckyshadows.net",
            "power.ddnss.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.8",
        "overwrite.cli.url": "https:\/\/vmd64337.contaboserver.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": 104857600,
        "logfile": "\/daten\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 7",
        "app_install_overwrite": [
            "keeweb",
            "deck",
            "spreed",
            "bookmarks",
            "music",
            "unsplash",
            "onlyoffice",
            "breezedark",
            "documentserver_community",
            "bruteforcesettings",
            "news",
            "riotchat"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "default_phone_region": "DE",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Web server error log**
```
nothing relevant (afaik)
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
{"reqId":"cLJZ2n0D72kyypHkINCS","level":3,"time":"2023-12-09T16:25:01+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","userAgent":"--","version":"28.0.0.8","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":146,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":173,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":443,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":64,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":56,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"function":"OC\\AppFramework\\Bootstrap\\{closure}","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":66,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/nextcloud/apps/bookmarks/lib/AppInfo/Application.php","line":104,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\Bookmarks\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/App/AppManager.php","line":434,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/private/App/AppManager.php","line":213,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":125,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":55,"function":"loadApps","class":"OC_App","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":135,"message":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist","exception":{},"CustomMessage":"Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist"}}
```

Please advice what information may be useful for further investigation, I am happy to help.
(most likely a duplicate of #2102)

**Comment by s256** [comment] 2023-12-12 14:21
same here on debian 12 with NC 27.1.2 and NC 28.0.0:
```
{
    "reqId": "oHVI6Xz43gEUYvF3XKQ1",
    "level": 3,
    "time": "2023-12-12T14:18:48+00:00",
    "remoteAddr": "fdgfgfg",
    "user": "foo",
    "app": "no app in context",
    "method": "GET",
    "url": "/ocs/v2.php/apps/notifications/api/v2/notifications",
    "message": "Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; rv:120.0) Gecko/20100101 Firefox/120.0",
    "version": "28.0.0.11",
    "exception": {
        "Exception": "OC\\AppFramework\\Utility\\QueryNotFoundException",
        "Message": "Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 146,
                "function": "resolve",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/ServerContainer.php",
                "line": 173,
                "function": "query",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php",
                "line": 443,
                "function": "query",
                "class": "OC\\ServerContainer",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 64,
                "function": "query",
                "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Bootstrap/FunctionInjector.php",
                "line": 56,
                "function": "get",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->"
            },
            {
                "function": "OC\\AppFramework\\Bootstrap\\{closure}",
                "class": "OC\\AppFramework\\Bootstrap\\FunctionInjector",
                "type": "->",
                "args": [
                    "*** sensitive parameters replaced ***"
                ]
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Bootstrap/FunctionInjector.php",
                "line": 45,
                "function": "array_map"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Bootstrap/BootContext.php",
                "line": 50,
                "function": "injectFn",
                "class": "OC\\AppFramework\\Bootstrap\\FunctionInjector",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/apps/bookmarks/lib/AppInfo/Application.php",
                "line": 104,
                "function": "injectFn",
                "class": "OC\\AppFramework\\Bootstrap\\BootContext",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php",
                "line": 200,
                "function": "boot",
                "class": "OCA\\Bookmarks\\AppInfo\\Application",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/App/AppManager.php",
                "line": 434,
                "function": "bootApp",
                "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/App/AppManager.php",
                "line": 213,
                "function": "loadApp",
                "class": "OC\\App\\AppManager",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/lib/private/legacy/OC_App.php",
                "line": 125,
                "function": "loadApps",
                "class": "OC\\App\\AppManager",
                "type": "->"
            },
            {
                "file": "/var/www/foo.bar/htdocs/ocs/v1.php",
                "line": 59,
                "function": "loadApps",
                "class": "OC_App",
                "type": "::"
            },
            {
                "file": "/var/www/foo.bar/htdocs/ocs/v2.php",
                "line": 23,
                "args": [
                    "/var/www/foo.bar/htdocs/ocs/v1.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/var/www/foo.bar/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php",
        "Line": 135,
        "message": "Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist",
        "exception": {},
        "CustomMessage": "Could not boot bookmarks: Could not resolve symfonyAdapter! Class \"symfonyAdapter\" does not exist"
    }
}

```

Bit confusing that the ticket is marked as done in the board but the issue is still open ;)

**Comment by GVLLIFESTYLE** [comment] 2023-12-12 15:32
same here.

**Comment by Killerjoe** [comment] 2023-12-12 21:52
Same here

**Comment by adhoc-post** [comment] 2023-12-13 06:40
Same same

**Comment by joshtrichards** [comment] 2023-12-13 16:11
Duplicate of #2102

**Closed as not planned by joshtrichards** 2023-12-13 16:11 UTC
Labels: bug
