### ISSUE TITLE
How do I unfilter my bookmarks?

### ISSUE THREAD

**Issue by jpschewe** [nextcloud/bookmarks#168] opened 2015-07-09 00:09 UTC
Once I click on a tag on the left, my bookmarks are filtered to just that tag. How do I get back to the original list of tags without reloading the page?

**Comment by blizzz** [comment] 2015-07-09 08:37
Currently by loading bookmark app again.

**Comment by jancborchardt** [comment] 2015-07-09 11:04
@blizzz the tags sidebar should behave like the sidebar of other apps: Every tag is a category, and there is a top category »All« which shows everything (unfilter). Ok?

**Comment by blizzz** [comment] 2015-07-10 17:39
@jancborchardt as in files?

![screenshot1](https://cloud.githubusercontent.com/assets/2184312/8624780/c97e9ed0-273a-11e5-89f6-88f1b713f306.jpg)

We need an input filter element as many tags are more than likely (cf. https://github.com/owncloud/bookmarks/pull/133).  And we should decide between showing everything and lazy loading of moar tags. Do we have similar anywhere? In User Management, we just show all groups. For filtering, we could utilize the search field? User Management has a filter field of its own, but for Files it works like this. But then (when using search field) we'd filter bookmarks also.

**Comment by jancborchardt** [comment] 2015-07-11 05:21
Yeah, as in files. Or maybe Tasks is the better comparison since it's more similar, you can create lists, add items, etc.

For search, definitely use the main search bar as we do in Files and Mail. With it the content (the bookmarkks) should be filtered as you type. While that happens, the list of tags in the left can be updated to reflect the tags present in the items in the search results and number of elements with these tags.

**Comment by theWatchmen** [comment] 2015-07-15 10:19
I remember in previous version of the plugin that when you added a tag filter, a label would appear on top with an "x" that would allow to remove the filter for that tag. Imho it was a clean solution and consistent with the current design. If there's anything I can to do help/test, please let me know.

**Comment by jancborchardt** [comment] 2015-07-15 13:17
As I said above it should be exactly like in Files, and other apps like Tasks, Mail, News:
* Have one »All bookmarks« entry on top of the list, and the list of tags below. This list is always the same no matter which entry is selected.
* When a sidebar entry (tag) is clicked, the content area should show only the entries for that respective tag. You can return to show all bookmarks by clicking on the »All bookmarks« entry of course, or on any other tag.
* The tags are sorted by number of bookmarks tagged with them (importance/usage).

**Comment by blizzz** [comment] 2015-07-15 17:21
@jancborchardt 

- Next to "All Bookmarks" we should have "Untagged Bookmarks" as well.
- We also need an approach to select multiple tags. I would vote now to be able to click on multiple tags, and they will be just sorted on top as long as they are active. Clicking again will unselect them. It's usefull if you have fantastillion bookmarks tagged "linux" and you further want to see "programming" topics, but not "administration", for instance.

**Comment by jancborchardt** [comment] 2015-07-15 17:29
> Next to "All Bookmarks" we should have "Untagged Bookmarks" as well.

Yes. Let’s put it below »All bookmarks« and simply call it »Untagged«.


> We also need an approach to select multiple tags. I would vote now to be able to click on multiple tags, and they will be just sorted on top as long as they are active. Clicking again will unselect them. It's usefull if you have fantastillion bookmarks tagged "linux" and you further want to see "programming" topics, but not "administration", for instance.

Let’s for now go with the default ownCloud app behavior of only being able to select one sidebar element. We can enhance that further in the future. For example when having selected a tag, every other tag has a plus button or something like that in the row – only when clicked that, both tags are shown together.

**Comment by blizzz** [comment] 2015-07-15 19:40
>> We also need an approach to select multiple tags. I would vote now to be able to click on multiple tags, and they will be just sorted on top as long as they are active. Clicking again will unselect them. It's usefull if you have fantastillion bookmarks tagged "linux" and you further want to see "programming" topics, but not "administration", for instance.

> Let’s for now go with the default ownCloud app behavior of only being able to select one sidebar element. We can enhance that further in the future. For example when having selected a tag, every other tag has a plus button or something like that in the row – only when clicked that, both tags are shown together.

I am already halfway there:

![screenshot-bookmarklet1](https://cloud.githubusercontent.com/assets/2184312/8708028/d3b615a6-2b39-11e5-985a-22d5d34cfb21.jpg)

![screenshot-bookmarklet1](https://cloud.githubusercontent.com/assets/2184312/8708033/e227d3ea-2b39-11e5-83ec-d945cdd43815.jpg)

![screenshot-bookmarklet1](https://cloud.githubusercontent.com/assets/2184312/8708042/ee816c6e-2b39-11e5-869e-372a3709cd98.jpg)

**Comment by blizzz** [comment] 2015-07-15 19:41
Having it not would be a regression.

**Comment by jancborchardt** [comment] 2015-07-15 19:41
It wouldn’t be a regression. It would be simplifying the app. Right now the app has modes, and the sidebar changes _a lot_ depending on which tag you have selected. That happens with _no_ other app.

**Comment by blizzz** [comment] 2015-07-15 20:05
Simplifying does not makes sense on that part as it's something that you do use regularly when browsing bookmarks by tabs. Agreed, other apps do not behave like that. Well, then we could differently with the content area, but I am not having an elegant solution for that right now. Other than having an editable breadcrumb like bar on top, with some typeahead. Would leave All Bookmarks and Untagged in the Sidebar. Reserves space for future special categories, be it Shared, Favorites or whatever. Alas, managing (renaming, deleting) would not be too nice this way, that "breadcrumb"-thingy would need to hold that. And you'd miss an overview about existing tags, if that is of any importance (personally not as much as it's important to narrow down bookmarks with multiple tags).

**Comment by jancborchardt** [comment] 2015-07-15 20:23
> it's something that you do use regularly when browsing bookmarks by tags

Well – let’s compare it with other systems which use tags. For example the most prominent one: Gmail. They do it exactly like I describe. Changing the sidebar is confusing and introduces a mode into the sidebar.

Switching between tags is arguably something you do more often than combining two tags. And this is made way more cumbersome by the current approach.

**Comment by africanforest** [comment] 2015-07-23 07:49
Not only can filters only be reset by reloading the page, but also, at least for me, after applying a filter, all other tags are disappearing from the menu! 

Of course there should be a menu item "All Tags" as well as all existing tags permanently visible in the menu pane.

**Comment by jancborchardt** [comment] 2015-07-23 10:19
@blizzz any work in progress PR of this? As you see the left sidebar changing is very confusing.

**Comment by shaneonabike** [comment] 2015-11-18 18:37
I "think" the initial implementation was developed as a drill-down motif. I agree that not changing the left bar makes a load of sense. It's what we also see in news readers (I realize that's not the same idea but it's the same kind of tagging concept). From an accessibility perspective, having this not change will make it more. Certaintly, having a All bookmarks for screen readers makes this app waaay more usable for those with accessibility needs.

(Y)

**Comment by jbinard** [comment] 2016-04-21 13:10
Any news about the improvement of tag filter ?
Currently, it's very confusing to be forced to reload the page to retrieve the complete list of bookmarks.

**Comment by shaneonabike** [comment] 2016-04-21 13:27
Agreed! I think as a usability issue and something that owncloud tends
to really address we need to rethink this one. I'll see if I can't
brainstorm some ideas.

On 2016-04-21 10:10 AM, Johan Binard wrote:
>
> Any news about the improvement of tag filter ?
> Currently, it's very confusing to be forced to reload the page to
> retrieve the complete list of bookmarks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/bookmarks/issues/168#issuecomment-212912384>
>

-- 

Shane Bill

Web Developer & Consultant

Bees on a Bike

E-mail 	shane@beesonabike.com <mailto:shane@beesonabike.com>
Mobile 	(514) 608-8068
Phone 	(418) 969-2334
More information @ Bees on a Bike 	https://beesonabike.com

**Comment by jancborchardt** [comment] 2016-07-01 09:01
Everyone, please review the pull request by @TtuxX at #261! :)

**Comment by blizzz** [comment] 2016-08-07 21:11
fyi, #261 got merged

**Comment by guitargurus** [comment] 2016-10-24 03:29
I would also like a way to reset back to view all after deselecting all tabs.  Thank you.

**Closed** 2018-03-12 18:11 UTC
Labels: enhancement, ui
