### ISSUE TITLE
Bookmarks 0.16.2 unusable on mobile iOS (can't scroll)

### ISSUE THREAD

**Issue by mikec83** [nextcloud/bookmarks#670] opened 2019-03-18 14:40 UTC
### Steps to reproduce
1. Open bookmarks on an iOS web browser (Chrome or Safari)
2. User can not scroll down list of bookmarks (the UI has some sort of weird drag/drop stuff going on if you try to drag and scroll.

### Expected behaviour
Dragging your finger on the screen should scroll down your list of bookmarks.

### Actual behaviour
The app acts as if you are trying to drag and drop a bookmark somehwere.  Unable to scroll.

**Comment by marcelklehr** [comment] 2019-03-18 16:59
Thank you for reporting this and sorry for the inconvenience! This is a duplicate of #667

**Closed as completed by marcelklehr** 2019-03-18 16:59 UTC
