### ISSUE TITLE
Can´t install from within my own nextclouds "app store"

### ISSUE THREAD

**Issue by wahoonie76** [nextcloud/bookmarks#1708] opened 2021-12-10 16:32 UTC
Hi,

I just wanted to install your app from my nextcloud installation in it gets an error: `"Client error: ´GET https://github.com/nextcloud/bookmarks/releases/download/10.0.3/bookmarks-10.0.3.tar.gz´ resulted in a ´404 Not Found´ response: Not Found "`.

If comparing the above url with the download url from github (`https://github.com/nextcloud/bookmarks/releases/download/v10.0.3/bookmarks-10.0.3.tar.gz`) is a difference to see: in githubs url is a "v" before the version number ("10.0.3").

Maybe this is the error in my case?!

How can I repair the install script to correct the url in my own installation?

Thank in advance for helping.

Greets

wahoonie

for better comparing the urls:
`https://github.com/nextcloud/bookmarks/releases/download/10.0.3/bookmarks-10.0.3.tar.gz` (error message)
`https://github.com/nextcloud/bookmarks/releases/download/v10.0.3/bookmarks-10.0.3.tar.gz` (github download url)

**Comment by arnowelzel** [comment] 2021-12-10 16:33
Seems to be a duplicate of #1707

**Comment by arnowelzel** [comment] 2021-12-10 16:35
You can download the file manually and extract it to your "apps" folder in Nextcloud. The result should be then in "apps/bookmarks" Then you should see the app in the list of "disabled apps" and can activate from there.

**Comment by marcelklehr** [comment] 2021-12-11 08:47
Should be fixed now.

**Closed as completed by marcelklehr** 2021-12-11 08:47 UTC
Labels: bug
