### ISSUE TITLE
Bookmarks via bookmarklet truncated

### ISSUE THREAD

**Issue by stueja** [nextcloud/bookmarks#486] opened 2018-05-01 09:13 UTC
### Steps to reproduce
1. point your browser to a site containing parameters (e. g. https://www.thetvdb.com/?tab=season&seriesid=83214&seasonid=743466&lid=14)
2. press the "Add to Cloud" bookmarklet
3. Check the URL in the URL input box

### Expected behaviour
The complete URL should be saved by the bookmarklet

### Actual behaviour
The URL is truncated after invoking the bookmarklet (in this example, on the first ampersand: https://www.thetvdb.com/?tab=season)

### Server configuration

**Operating system**:
Arch Linux

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.2.5

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Bookmarks version:** (see Nextcloud apps page)
0.11.0

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
Enabled:
  - activity: 2.6.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - music: 0.5.6
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - radio
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.js73.local"
        ],
        "overwrite.cli.url": "https:\/\/cloud.js73.local",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

```
**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local

**Are you using encryption:** yes/no
yes, TLS between browser and nginx

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Firefox 59.0.2

**Operating system:**
Arch Linux

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
no message of the date I was experiencing the described issue. 
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment] 2018-05-01 20:13
Thanks for reporting! I cannot reproduce this with the upcoming version and the URL you provided, so I dare say this has been fixed already, but not released, yet. Hence, I'm closing this for now. Feel free to shout if the issue persists with the new version :)

**Closed as completed by marcelklehr** 2018-05-01 20:13 UTC
